"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    const items = [
      {
        "firstName": "Eléa",
        "lastName": "Rosthorn",
        "email": "brosthorn0@geocities.com",
        "mobile": "415-288-4659",
        "address": "92 Chive Parkway",
        "country": "United States",
        "city": "San Francisco",
        "state": "California",
        "zipCode": "VE-V",
        "isDefault": false,
        "userId": 1
      }, {
        "firstName": "Cunégonde",
        "lastName": "Kaaskooper",
        "email": "ckaaskooper1@cafepress.com",
        "mobile": "615-193-0868",
        "address": "6780 Eastwood Trail",
        "country": "United States",
        "city": "Memphis",
        "state": "Tennessee",
        "zipCode": "US-AK",
        "isDefault": false,
        "userId": 2
      }, {
        "firstName": "Clélia",
        "lastName": "O Sullivan",
        "email": "bosullivan2@umn.edu",
        "mobile": "330-192-5309",
        "address": "9 Northview Road",
        "country": "United States",
        "city": "Akron",
        "state": "Ohio",
        "zipCode": "US-AK",
        "isDefault": true,
        "userId": 3
      }, {
        "firstName": "Tán",
        "lastName": "Sharkey",
        "email": "bsharkey3@hud.gov",
        "mobile": "615-578-9242",
        "address": "84 Stephen Lane",
        "country": "United States",
        "city": "Nashville",
        "state": "Tennessee",
        "zipCode": "ID-ST",
        "isDefault": true,
        "userId": 4
      }, {
        "firstName": "Renée",
        "lastName": "Rickett",
        "email": "crickett4@google.ru",
        "mobile": "317-410-7355",
        "address": "0 Derek Avenue",
        "country": "United States",
        "city": "Indianapolis",
        "state": "Indiana",
        "zipCode": "US-VA",
        "isDefault": true,
        "userId": 5
      }, {
        "firstName": "Maëlys",
        "lastName": "Bayldon",
        "email": "rbayldon5@163.com",
        "mobile": "309-488-2398",
        "address": "88 Laurel Alley",
        "country": "United States",
        "city": "Peoria",
        "state": "Illinois",
        "zipCode": "BO-S",
        "isDefault": true,
        "userId": 6
      }, {
        "firstName": "Zoé",
        "lastName": "Ellicombe",
        "email": "fellicombe6@friendfeed.com",
        "mobile": "713-168-6275",
        "address": "929 Lighthouse Bay Crossing",
        "country": "United States",
        "city": "Houston",
        "state": "Texas",
        "zipCode": "SA-14",
        "isDefault": false,
        "userId": 7
      }, {
        "firstName": "Joséphine",
        "lastName": "Beebee",
        "email": "abeebee7@prnewswire.com",
        "mobile": "601-734-5494",
        "address": "56 Esch Circle",
        "country": "United States",
        "city": "Hattiesburg",
        "state": "Mississippi",
        "zipCode": "YE-SD",
        "isDefault": true,
        "userId": 8
      }, {
        "firstName": "Adélaïde",
        "lastName": "Thaw",
        "email": "tthaw8@china.com.cn",
        "mobile": "515-124-5564",
        "address": "685 Norway Maple Terrace",
        "country": "United States",
        "city": "Des Moines",
        "state": "Iowa",
        "zipCode": "AU-NT",
        "isDefault": true,
        "userId": 9
      }, {
        "firstName": "Maïté",
        "lastName": "Simonian",
        "email": "asimonian9@ocn.ne.jp",
        "mobile": "623-568-1689",
        "address": "02 Porter Crossing",
        "country": "United States",
        "city": "Phoenix",
        "state": "Arizona",
        "zipCode": "US-CA",
        "isDefault": true,
        "userId": 10
      }, {
        "firstName": "Laurène",
        "lastName": "Biasioli",
        "email": "abiasiolia@freewebs.com",
        "mobile": "651-416-6499",
        "address": "15565 Buell Park",
        "country": "United States",
        "city": "Saint Paul",
        "state": "Minnesota",
        "zipCode": "FR-B",
        "isDefault": true,
        "userId": 11
      }, {
        "firstName": "Léonore",
        "lastName": "Thuillier",
        "email": "fthuillierb@imgur.com",
        "mobile": "540-555-2350",
        "address": "19075 Eliot Court",
        "country": "United States",
        "city": "Roanoke",
        "state": "Virginia",
        "zipCode": "IN-WB",
        "isDefault": true,
        "userId": 12
      }, {
        "firstName": "Lén",
        "lastName": "Brooke",
        "email": "gbrookec@mtv.com",
        "mobile": "504-433-1555",
        "address": "109 Welch Terrace",
        "country": "United States",
        "city": "Metairie",
        "state": "Louisiana",
        "zipCode": "GT-GU",
        "isDefault": false,
        "userId": 13
      }, {
        "firstName": "Clémentine",
        "lastName": "Keitley",
        "email": "skeitleyd@ebay.com",
        "mobile": "734-851-1454",
        "address": "7727 Hudson Street",
        "country": "United States",
        "city": "Ann Arbor",
        "state": "Michigan",
        "zipCode": "CA-SK",
        "isDefault": true,
        "userId": 14
      }, {
        "firstName": "Maëlyss",
        "lastName": "Pavluk",
        "email": "mpavluke@wufoo.com",
        "mobile": "731-478-1882",
        "address": "55448 Nevada Road",
        "country": "United States",
        "city": "Jackson",
        "state": "Tennessee",
        "zipCode": "US-AK",
        "isDefault": true,
        "userId": 15
      }, {
        "firstName": "Vénus",
        "lastName": "Lambdin",
        "email": "rlambdinf@marketwatch.com",
        "mobile": "202-729-2580",
        "address": "1 Russell Point",
        "country": "United States",
        "city": "Washington",
        "state": "District of Columbia",
        "zipCode": "IR-28",
        "isDefault": false,
        "userId": 16
      }, {
        "firstName": "Célia",
        "lastName": "Wildey",
        "email": "jwildeyg@apache.org",
        "mobile": "404-236-9684",
        "address": "2336 Morningstar Center",
        "country": "United States",
        "city": "Atlanta",
        "state": "Georgia",
        "zipCode": "PG-WHM",
        "isDefault": false,
        "userId": 17
      }, {
        "firstName": "Kallisté",
        "lastName": "Vaissiere",
        "email": "mvaissiereh@delicious.com",
        "mobile": "682-423-8369",
        "address": "426 Meadow Ridge Junction",
        "country": "United States",
        "city": "Fort Worth",
        "state": "Texas",
        "zipCode": "MX-CHP",
        "isDefault": true,
        "userId": 18
      }, {
        "firstName": "Pål",
        "lastName": "Abelevitz",
        "email": "zabelevitzi@businesswire.com",
        "mobile": "513-511-2486",
        "address": "7 High Crossing Drive",
        "country": "United States",
        "city": "Cincinnati",
        "state": "Ohio",
        "zipCode": "CA-QC",
        "isDefault": true,
        "userId": 19
      }, {
        "firstName": "Thérèsa",
        "lastName": "Abriani",
        "email": "eabrianij@elpais.com",
        "mobile": "559-614-9920",
        "address": "133 Hoepker Court",
        "country": "United States",
        "city": "Fresno",
        "state": "California",
        "zipCode": "TH-16",
        "isDefault": true,
        "userId": 20
      }, {
        "firstName": "Yóu",
        "lastName": "Skyme",
        "email": "bskymek@google.de",
        "mobile": "915-554-5565",
        "address": "93 Sullivan Circle",
        "country": "United States",
        "city": "El Paso",
        "state": "Texas",
        "zipCode": "RU-PSK",
        "isDefault": false,
        "userId": 21
      }, {
        "firstName": "Yáo",
        "lastName": "Skones",
        "email": "bskonesl@sciencedirect.com",
        "mobile": "434-907-1237",
        "address": "942 Anniversary Plaza",
        "country": "United States",
        "city": "Durham",
        "state": "North Carolina",
        "zipCode": "ZA-WC",
        "isDefault": false,
        "userId": 22
      }, {
        "firstName": "Esbjörn",
        "lastName": "McPhelimy",
        "email": "cmcphelimym@netlog.com",
        "mobile": "415-493-9136",
        "address": "77802 Mcbride Pass",
        "country": "United States",
        "city": "San Francisco",
        "state": "California",
        "zipCode": "US-CA",
        "isDefault": true,
        "userId": 23
      }, {
        "firstName": "Publicité",
        "lastName": "Karmel",
        "email": "nkarmeln@patch.com",
        "mobile": "402-452-1628",
        "address": "14581 Kings Drive",
        "country": "United States",
        "city": "Omaha",
        "state": "Nebraska",
        "zipCode": "CA-QC",
        "isDefault": false,
        "userId": 24
      }, {
        "firstName": "Maïwenn",
        "lastName": "Nuemann",
        "email": "lnuemanno@jugem.jp",
        "mobile": "718-372-5638",
        "address": "25536 Golf View Avenue",
        "country": "United States",
        "city": "Flushing",
        "state": "New York",
        "zipCode": "US-NE",
        "isDefault": true,
        "userId": 25
      }, {
        "firstName": "Bérangère",
        "lastName": "Brawson",
        "email": "fbrawsonp@flavors.me",
        "mobile": "720-387-7901",
        "address": "82273 South Alley",
        "country": "United States",
        "city": "Denver",
        "state": "Colorado",
        "zipCode": "ZM-06",
        "isDefault": true,
        "userId": 26
      }, {
        "firstName": "Clélia",
        "lastName": "Ballefant",
        "email": "lballefantq@va.gov",
        "mobile": "251-419-5308",
        "address": "897 Lakewood Alley",
        "country": "United States",
        "city": "Mobile",
        "state": "Alabama",
        "zipCode": "CN-45",
        "isDefault": true,
        "userId": 27
      }, {
        "firstName": "Stévina",
        "lastName": "Coyte",
        "email": "gcoyter@people.com.cn",
        "mobile": "570-849-4985",
        "address": "81 Petterle Pass",
        "country": "United States",
        "city": "Wilkes Barre",
        "state": "Pennsylvania",
        "zipCode": "BZ-SC",
        "isDefault": true,
        "userId": 28
      }, {
        "firstName": "Thérèsa",
        "lastName": "Bromet",
        "email": "ebromets@examiner.com",
        "mobile": "718-961-2432",
        "address": "1 Ramsey Alley",
        "country": "United States",
        "city": "Brooklyn",
        "state": "New York",
        "zipCode": "PK-PB",
        "isDefault": false,
        "userId": 29
      }, {
        "firstName": "Léana",
        "lastName": "Kiley",
        "email": "jkileyt@time.com",
        "mobile": "419-256-0547",
        "address": "81610 Marquette Circle",
        "country": "United States",
        "city": "Mansfield",
        "state": "Ohio",
        "zipCode": "RS-20",
        "isDefault": false,
        "userId": 30
      }, {
        "firstName": "Michèle",
        "lastName": "Amiable",
        "email": "tamiableu@about.com",
        "mobile": "817-510-7149",
        "address": "307 Blaine Circle",
        "country": "United States",
        "city": "Denton",
        "state": "Texas",
        "zipCode": "AU-QLD",
        "isDefault": false,
        "userId": 31
      }, {
        "firstName": "Personnalisée",
        "lastName": "Kevis",
        "email": "bkevisv@mac.com",
        "mobile": "617-859-4681",
        "address": "75 Hazelcrest Park",
        "country": "United States",
        "city": "Boston",
        "state": "Massachusetts",
        "zipCode": "IN-JH",
        "isDefault": false,
        "userId": 32
      }, {
        "firstName": "Mårten",
        "lastName": "Itzik",
        "email": "bitzikw@redcross.org",
        "mobile": "405-443-1678",
        "address": "323 Barby Center",
        "country": "United States",
        "city": "Oklahoma City",
        "state": "Oklahoma",
        "zipCode": "TD-TA",
        "isDefault": false,
        "userId": 33
      }, {
        "firstName": "Judicaël",
        "lastName": "Eads",
        "email": "eeadsx@pen.io",
        "mobile": "727-319-1893",
        "address": "66901 Clyde Gallagher Junction",
        "country": "United States",
        "city": "Saint Petersburg",
        "state": "Florida",
        "zipCode": "OM-ZA",
        "isDefault": true,
        "userId": 34
      }, {
        "firstName": "Laïla",
        "lastName": "Vlasyev",
        "email": "rvlasyevy@amazon.de",
        "mobile": "215-311-3412",
        "address": "03 Marcy Park",
        "country": "United States",
        "city": "Philadelphia",
        "state": "Pennsylvania",
        "zipCode": "AU-QLD",
        "isDefault": false,
        "userId": 35
      }, {
        "firstName": "Audréanne",
        "lastName": "McOrkil",
        "email": "dmcorkilz@bloglines.com",
        "mobile": "972-994-7733",
        "address": "627 Memorial Drive",
        "country": "United States",
        "city": "Dallas",
        "state": "Texas",
        "zipCode": "AU-WA",
        "isDefault": false,
        "userId": 36
      }, {
        "firstName": "Kallisté",
        "lastName": "Bindin",
        "email": "cbindin10@buzzfeed.com",
        "mobile": "801-963-7563",
        "address": "626 Pepper Wood Terrace",
        "country": "United States",
        "city": "Salt Lake City",
        "state": "Utah",
        "zipCode": "CO-PUT",
        "isDefault": true,
        "userId": 37
      }, {
        "firstName": "Mahélie",
        "lastName": "Sizzey",
        "email": "msizzey11@mit.edu",
        "mobile": "915-207-8334",
        "address": "3535 South Park",
        "country": "United States",
        "city": "El Paso",
        "state": "Texas",
        "zipCode": "US-NM",
        "isDefault": false,
        "userId": 38
      }, {
        "firstName": "Magdalène",
        "lastName": "Veracruysse",
        "email": "sveracruysse12@weather.com",
        "mobile": "901-851-9998",
        "address": "428 Washington Park",
        "country": "United States",
        "city": "Memphis",
        "state": "Tennessee",
        "zipCode": "BR-RS",
        "isDefault": true,
        "userId": 39
      }, {
        "firstName": "Pål",
        "lastName": "Strachan",
        "email": "bstrachan13@cornell.edu",
        "mobile": "941-402-3740",
        "address": "3 Rieder Alley",
        "country": "United States",
        "city": "Bradenton",
        "state": "Florida",
        "zipCode": "AU-WA",
        "isDefault": false,
        "userId": 40
      }, {
        "firstName": "Estée",
        "lastName": "Swadlen",
        "email": "aswadlen14@tripod.com",
        "mobile": "615-107-8412",
        "address": "7897 Green Ridge Parkway",
        "country": "United States",
        "city": "Nashville",
        "state": "Tennessee",
        "zipCode": "BR-RS",
        "isDefault": false,
        "userId": 41
      }, {
        "firstName": "Clémentine",
        "lastName": "Gittis",
        "email": "cgittis15@fastcompany.com",
        "mobile": "937-320-9930",
        "address": "27549 Randy Avenue",
        "country": "United States",
        "city": "Dayton",
        "state": "Ohio",
        "zipCode": "FI-IS",
        "isDefault": true,
        "userId": 42
      }, {
        "firstName": "Marie-thérèse",
        "lastName": "Lippingwell",
        "email": "clippingwell16@themeforest.net",
        "mobile": "209-333-5735",
        "address": "040 Magdeline Parkway",
        "country": "United States",
        "city": "Modesto",
        "state": "California",
        "zipCode": "US-TX",
        "isDefault": false,
        "userId": 43
      }, {
        "firstName": "Miléna",
        "lastName": "Misk",
        "email": "fmisk17@nifty.com",
        "mobile": "214-538-8273",
        "address": "169 Knutson Place",
        "country": "United States",
        "city": "Dallas",
        "state": "Texas",
        "zipCode": "MZ-L",
        "isDefault": false,
        "userId": 44
      }, {
        "firstName": "Pélagie",
        "lastName": "Kubica",
        "email": "gkubica18@pcworld.com",
        "mobile": "305-866-7676",
        "address": "49161 Harper Place",
        "country": "United States",
        "city": "Miami",
        "state": "Florida",
        "zipCode": "US-AK",
        "isDefault": true,
        "userId": 45
      }, {
        "firstName": "Gaétane",
        "lastName": "Bannon",
        "email": "abannon19@blogs.com",
        "mobile": "727-697-9073",
        "address": "0 Dakota Alley",
        "country": "United States",
        "city": "Tampa",
        "state": "Florida",
        "zipCode": "SD-24",
        "isDefault": true,
        "userId": 46
      }, {
        "firstName": "Aurélie",
        "lastName": "O'Corrane",
        "email": "jocorrane1a@purevolume.com",
        "mobile": "727-399-9019",
        "address": "9750 Cardinal Pass",
        "country": "United States",
        "city": "Clearwater",
        "state": "Florida",
        "zipCode": "BO-S",
        "isDefault": true,
        "userId": 47
      }, {
        "firstName": "Solène",
        "lastName": "Rawkesby",
        "email": "crawkesby1b@hostgator.com",
        "mobile": "951-563-6087",
        "address": "5009 Norway Maple Point",
        "country": "United States",
        "city": "Moreno Valley",
        "state": "California",
        "zipCode": "NO-14",
        "isDefault": false,
        "userId": 48
      }, {
        "firstName": "Wá",
        "lastName": "Ayrs",
        "email": "rayrs1c@icio.us",
        "mobile": "678-991-1479",
        "address": "69068 Pankratz Road",
        "country": "United States",
        "city": "Lawrenceville",
        "state": "Georgia",
        "zipCode": "DE-BE",
        "isDefault": true,
        "userId": 49
      }, {
        "firstName": "Angélique",
        "lastName": "Cush",
        "email": "lcush1d@noaa.gov",
        "mobile": "702-260-3819",
        "address": "93648 Elka Point",
        "country": "United States",
        "city": "North Las Vegas",
        "state": "Nevada",
        "zipCode": "CA-NS",
        "isDefault": true,
        "userId": 50
      }, {
        "firstName": "Réservés",
        "lastName": "Handy",
        "email": "vhandy1e@goo.gl",
        "mobile": "949-569-2681",
        "address": "970 Texas Center",
        "country": "United States",
        "city": "Santa Ana",
        "state": "California",
        "zipCode": "BR-MT",
        "isDefault": true,
        "userId": 51
      }, {
        "firstName": "Médiamass",
        "lastName": "Daniels",
        "email": "jdaniels1f@theglobeandmail.com",
        "mobile": "847-279-7263",
        "address": "1 Lyons Point",
        "country": "United States",
        "city": "Palatine",
        "state": "Illinois",
        "zipCode": "GB-WLS",
        "isDefault": false,
        "userId": 52
      }, {
        "firstName": "Maëline",
        "lastName": "Decruse",
        "email": "fdecruse1g@buzzfeed.com",
        "mobile": "661-390-5606",
        "address": "8268 Starling Circle",
        "country": "United States",
        "city": "Bakersfield",
        "state": "California",
        "zipCode": "BR-PR",
        "isDefault": false,
        "userId": 53
      }, {
        "firstName": "Marie-ève",
        "lastName": "Officer",
        "email": "zofficer1h@craigslist.org",
        "mobile": "661-110-4779",
        "address": "82 Dayton Lane",
        "country": "United States",
        "city": "Burbank",
        "state": "California",
        "zipCode": "US-AK",
        "isDefault": true,
        "userId": 54
      }, {
        "firstName": "Kuí",
        "lastName": "Rowen",
        "email": "mrowen1i@rambler.ru",
        "mobile": "323-524-7218",
        "address": "446 Parkside Road",
        "country": "United States",
        "city": "Los Angeles",
        "state": "California",
        "zipCode": "KI-L",
        "isDefault": true,
        "userId": 55
      }, {
        "firstName": "Léane",
        "lastName": "McGrale",
        "email": "amcgrale1j@java.com",
        "mobile": "949-252-6414",
        "address": "06 Manitowish Circle",
        "country": "United States",
        "city": "Irvine",
        "state": "California",
        "zipCode": "US-TX",
        "isDefault": true,
        "userId": 56
      }, {
        "firstName": "Märta",
        "lastName": "Ashwin",
        "email": "bashwin1k@fda.gov",
        "mobile": "918-395-2867",
        "address": "47 Messerschmidt Plaza",
        "country": "United States",
        "city": "Tulsa",
        "state": "Oklahoma",
        "zipCode": "NO-20",
        "isDefault": false,
        "userId": 57
      }, {
        "firstName": "Andréanne",
        "lastName": "Every",
        "email": "fevery1l@so-net.ne.jp",
        "mobile": "610-287-3333",
        "address": "7965 Bashford Park",
        "country": "United States",
        "city": "Philadelphia",
        "state": "Pennsylvania",
        "zipCode": "US-IL",
        "isDefault": false,
        "userId": 58
      }, {
        "firstName": "Anaïs",
        "lastName": "Mynett",
        "email": "lmynett1m@google.com.au",
        "mobile": "508-625-7276",
        "address": "1054 Dahle Place",
        "country": "United States",
        "city": "New Bedford",
        "state": "Massachusetts",
        "zipCode": "AU-WA",
        "isDefault": false,
        "userId": 59
      }, {
        "firstName": "Adélie",
        "lastName": "Lemanu",
        "email": "dlemanu1n@about.me",
        "mobile": "619-462-1189",
        "address": "6528 Charing Cross Place",
        "country": "United States",
        "city": "San Diego",
        "state": "California",
        "zipCode": "CO-MET",
        "isDefault": true,
        "userId": 60
      }, {
        "firstName": "Mélissandre",
        "lastName": "D'Onise",
        "email": "adonise1o@weather.com",
        "mobile": "616-858-1137",
        "address": "486 Spohn Plaza",
        "country": "United States",
        "city": "Grand Rapids",
        "state": "Michigan",
        "zipCode": "CN-52",
        "isDefault": true,
        "userId": 61
      }, {
        "firstName": "Kuí",
        "lastName": "Doorbar",
        "email": "odoorbar1p@canalblog.com",
        "mobile": "614-348-0812",
        "address": "71 Village Green Terrace",
        "country": "United States",
        "city": "Columbus",
        "state": "Ohio",
        "zipCode": "BR-SC",
        "isDefault": true,
        "userId": 62
      }, {
        "firstName": "Thérèse",
        "lastName": "Rodenhurst",
        "email": "mrodenhurst1q@dropbox.com",
        "mobile": "801-206-3718",
        "address": "375 Kennedy Park",
        "country": "United States",
        "city": "Salt Lake City",
        "state": "Utah",
        "zipCode": "CA-QC",
        "isDefault": true,
        "userId": 63
      }, {
        "firstName": "Marie-josée",
        "lastName": "Mercey",
        "email": "gmercey1r@slideshare.net",
        "mobile": "205-465-2787",
        "address": "1 Veith Center",
        "country": "United States",
        "city": "Birmingham",
        "state": "Alabama",
        "zipCode": "US-MA",
        "isDefault": true,
        "userId": 64
      }, {
        "firstName": "Mégane",
        "lastName": "Bibby",
        "email": "sbibby1s@nyu.edu",
        "mobile": "713-290-1151",
        "address": "844 Dayton Road",
        "country": "United States",
        "city": "Houston",
        "state": "Texas",
        "zipCode": "US-MI",
        "isDefault": true,
        "userId": 65
      }, {
        "firstName": "Mélina",
        "lastName": "Willey",
        "email": "cwilley1t@comsenz.com",
        "mobile": "404-586-9415",
        "address": "4 Columbus Terrace",
        "country": "United States",
        "city": "Duluth",
        "state": "Georgia",
        "zipCode": "LC-02",
        "isDefault": true,
        "userId": 66
      }, {
        "firstName": "Maïté",
        "lastName": "Codlin",
        "email": "gcodlin1u@state.tx.us",
        "mobile": "713-358-1429",
        "address": "27057 Lukken Avenue",
        "country": "United States",
        "city": "Houston",
        "state": "Texas",
        "zipCode": "US-ND",
        "isDefault": true,
        "userId": 67
      }, {
        "firstName": "Léonie",
        "lastName": "Oulett",
        "email": "loulett1v@salon.com",
        "mobile": "727-959-4955",
        "address": "24995 Monument Alley",
        "country": "United States",
        "city": "Clearwater",
        "state": "Florida",
        "zipCode": "GB-ENG",
        "isDefault": false,
        "userId": 68
      }, {
        "firstName": "Léane",
        "lastName": "Sangar",
        "email": "psangar1w@posterous.com",
        "mobile": "979-682-3641",
        "address": "9 Old Shore Alley",
        "country": "United States",
        "city": "Bryan",
        "state": "Texas",
        "zipCode": "US-CA",
        "isDefault": true,
        "userId": 69
      }, {
        "firstName": "Léa",
        "lastName": "Luberti",
        "email": "aluberti1x@edublogs.org",
        "mobile": "574-121-9555",
        "address": "7249 Holmberg Plaza",
        "country": "United States",
        "city": "South Bend",
        "state": "Indiana",
        "zipCode": "RU-IN",
        "isDefault": false,
        "userId": 70
      }, {
        "firstName": "Maï",
        "lastName": "Sheal",
        "email": "bsheal1y@elpais.com",
        "mobile": "808-924-0204",
        "address": "5 Golf Street",
        "country": "United States",
        "city": "Honolulu",
        "state": "Hawaii",
        "zipCode": "GQ-LI",
        "isDefault": true,
        "userId": 71
      }, {
        "firstName": "Célia",
        "lastName": "Zamora",
        "email": "ezamora1z@php.net",
        "mobile": "757-645-6551",
        "address": "497 Laurel Terrace",
        "country": "United States",
        "city": "Norfolk",
        "state": "Virginia",
        "zipCode": "UA-32",
        "isDefault": true,
        "userId": 72
      }, {
        "firstName": "Méng",
        "lastName": "Lerwell",
        "email": "ilerwell20@bandcamp.com",
        "mobile": "954-723-4770",
        "address": "2 Bellgrove Place",
        "country": "United States",
        "city": "Miami",
        "state": "Florida",
        "zipCode": "US-LA",
        "isDefault": false,
        "userId": 73
      }, {
        "firstName": "Laurélie",
        "lastName": "Scougall",
        "email": "dscougall21@webs.com",
        "mobile": "206-485-2348",
        "address": "3 Darwin Hill",
        "country": "United States",
        "city": "Seattle",
        "state": "Washington",
        "zipCode": "DE-NW",
        "isDefault": true,
        "userId": 74
      }, {
        "firstName": "Cunégonde",
        "lastName": "Gulland",
        "email": "egulland22@icq.com",
        "mobile": "916-976-9267",
        "address": "551 Elgar Crossing",
        "country": "United States",
        "city": "Sacramento",
        "state": "California",
        "zipCode": "BR-SP",
        "isDefault": false,
        "userId": 75
      }, {
        "firstName": "Vénus",
        "lastName": "McGrae",
        "email": "gmcgrae23@sciencedaily.com",
        "mobile": "720-662-3396",
        "address": "5336 Dottie Crossing",
        "country": "United States",
        "city": "Denver",
        "state": "Colorado",
        "zipCode": "BR-SP",
        "isDefault": true,
        "userId": 76
      }, {
        "firstName": "Amélie",
        "lastName": "Mordie",
        "email": "imordie24@rambler.ru",
        "mobile": "269-602-3168",
        "address": "82 Lakewood Gardens Pass",
        "country": "United States",
        "city": "Kalamazoo",
        "state": "Michigan",
        "zipCode": "IN-AR",
        "isDefault": true,
        "userId": 77
      }, {
        "firstName": "Véronique",
        "lastName": "Moultrie",
        "email": "smoultrie25@fema.gov",
        "mobile": "760-590-5102",
        "address": "17 Brickson Park Plaza",
        "country": "United States",
        "city": "Carlsbad",
        "state": "California",
        "zipCode": "US-NH",
        "isDefault": true,
        "userId": 78
      }, {
        "firstName": "Illustrée",
        "lastName": "Fradgley",
        "email": "ffradgley26@mlb.com",
        "mobile": "706-265-4563",
        "address": "35716 Graedel Trail",
        "country": "United States",
        "city": "Athens",
        "state": "Georgia",
        "zipCode": "MY-13",
        "isDefault": false,
        "userId": 79
      }, {
        "firstName": "Véronique",
        "lastName": "Smalls",
        "email": "vsmalls27@paypal.com",
        "mobile": "850-555-1069",
        "address": "749 Stuart Court",
        "country": "United States",
        "city": "Tallahassee",
        "state": "Florida",
        "zipCode": "RU-KK",
        "isDefault": true,
        "userId": 80
      }, {
        "firstName": "Danièle",
        "lastName": "Vedishchev",
        "email": "mvedishchev28@scientificamerican.com",
        "mobile": "916-114-1534",
        "address": "22771 Hermina Lane",
        "country": "United States",
        "city": "Sacramento",
        "state": "California",
        "zipCode": "AF-ORU",
        "isDefault": true,
        "userId": 81
      }, {
        "firstName": "Laïla",
        "lastName": "Pimblotte",
        "email": "tpimblotte29@mac.com",
        "mobile": "786-610-6167",
        "address": "0743 Nelson Avenue",
        "country": "United States",
        "city": "Miami",
        "state": "Florida",
        "zipCode": "SB-CE",
        "isDefault": true,
        "userId": 82
      }, {
        "firstName": "Nadège",
        "lastName": "Ruffle",
        "email": "druffle2a@bandcamp.com",
        "mobile": "267-148-0051",
        "address": "7 David Point",
        "country": "United States",
        "city": "Philadelphia",
        "state": "Pennsylvania",
        "zipCode": "US-PA",
        "isDefault": true,
        "userId": 83
      }, {
        "firstName": "Thérèse",
        "lastName": "Robker",
        "email": "arobker2b@nyu.edu",
        "mobile": "941-456-4371",
        "address": "713 Loftsgordon Circle",
        "country": "United States",
        "city": "Bonita Springs",
        "state": "Florida",
        "zipCode": "US-SC",
        "isDefault": false,
        "userId": 84
      }, {
        "firstName": "Maïlys",
        "lastName": "Rentoll",
        "email": "hrentoll2c@amazon.co.uk",
        "mobile": "785-579-6365",
        "address": "35241 Hintze Court",
        "country": "United States",
        "city": "Topeka",
        "state": "Kansas",
        "zipCode": "AU-WA",
        "isDefault": false,
        "userId": 85
      }, {
        "firstName": "Vérane",
        "lastName": "Thomazin",
        "email": "cthomazin2d@soundcloud.com",
        "mobile": "215-112-1430",
        "address": "52019 Ohio Street",
        "country": "United States",
        "city": "Philadelphia",
        "state": "Pennsylvania",
        "zipCode": "AU-TAS",
        "isDefault": false,
        "userId": 86
      }, {
        "firstName": "Médiamass",
        "lastName": "Vassie",
        "email": "evassie2e@go.com",
        "mobile": "561-276-7911",
        "address": "1936 Waubesa Hill",
        "country": "United States",
        "city": "Boca Raton",
        "state": "Florida",
        "zipCode": "CL-AT",
        "isDefault": false,
        "userId": 87
      }, {
        "firstName": "Mahélie",
        "lastName": "Gwioneth",
        "email": "jgwioneth2f@unesco.org",
        "mobile": "415-224-7283",
        "address": "2086 Beilfuss Street",
        "country": "United States",
        "city": "San Francisco",
        "state": "California",
        "zipCode": "JP-37",
        "isDefault": false,
        "userId": 88
      }, {
        "firstName": "Örjan",
        "lastName": "Paulich",
        "email": "mpaulich2g@psu.edu",
        "mobile": "386-572-5649",
        "address": "20 Petterle Street",
        "country": "United States",
        "city": "Daytona Beach",
        "state": "Florida",
        "zipCode": "IO-U-A",
        "isDefault": true,
        "userId": 89
      }, {
        "firstName": "Lauréna",
        "lastName": "Aaron",
        "email": "daaron2h@lycos.com",
        "mobile": "352-984-0073",
        "address": "744 Porter Road",
        "country": "United States",
        "city": "Gainesville",
        "state": "Florida",
        "zipCode": "AU-NSW",
        "isDefault": false,
        "userId": 90
      }, {
        "firstName": "Maéna",
        "lastName": "Orpin",
        "email": "dorpin2i@jimdo.com",
        "mobile": "954-306-9822",
        "address": "81 Lakewood Drive",
        "country": "United States",
        "city": "Fort Lauderdale",
        "state": "Florida",
        "zipCode": "CL-BI",
        "isDefault": false,
        "userId": 91
      }, {
        "firstName": "Gaétane",
        "lastName": "Lente",
        "email": "glente2j@webs.com",
        "mobile": "682-692-0919",
        "address": "6616 Karstens Lane",
        "country": "United States",
        "city": "Fort Worth",
        "state": "Texas",
        "zipCode": "PG-WPD",
        "isDefault": false,
        "userId": 92
      }, {
        "firstName": "Rachèle",
        "lastName": "Bovey",
        "email": "pbovey2k@ted.com",
        "mobile": "713-906-7201",
        "address": "74 Hoffman Terrace",
        "country": "United States",
        "city": "Houston",
        "state": "Texas",
        "zipCode": "US-CA",
        "isDefault": false,
        "userId": 93
      }, {
        "firstName": "Anaëlle",
        "lastName": "Sporner",
        "email": "ssporner2l@rakuten.co.jp",
        "mobile": "209-472-9436",
        "address": "94 Walton Drive",
        "country": "United States",
        "city": "Fresno",
        "state": "California",
        "zipCode": "AU-QLD",
        "isDefault": false,
        "userId": 94
      }, {
        "firstName": "Kallisté",
        "lastName": "Wadeson",
        "email": "rwadeson2m@spiegel.de",
        "mobile": "828-739-1400",
        "address": "6 Roth Trail",
        "country": "United States",
        "city": "Asheville",
        "state": "North Carolina",
        "zipCode": "SL-S",
        "isDefault": false,
        "userId": 95
      }, {
        "firstName": "Lyséa",
        "lastName": "Glanville",
        "email": "iglanville2n@kickstarter.com",
        "mobile": "937-689-0249",
        "address": "479 Kropf Pass",
        "country": "United States",
        "city": "Dayton",
        "state": "Ohio",
        "zipCode": "US-IL",
        "isDefault": false,
        "userId": 96
      }, {
        "firstName": "Océane",
        "lastName": "Niesing",
        "email": "aniesing2o@com.com",
        "mobile": "202-682-9321",
        "address": "996 Quincy Circle",
        "country": "United States",
        "city": "Washington",
        "state": "District of Columbia",
        "zipCode": "US-IL",
        "isDefault": true,
        "userId": 97
      }, {
        "firstName": "Angèle",
        "lastName": "Ragsdale",
        "email": "tragsdale2p@stanford.edu",
        "mobile": "334-483-7241",
        "address": "98 Annamark Road",
        "country": "United States",
        "city": "Montgomery",
        "state": "Alabama",
        "zipCode": "BR-RS",
        "isDefault": true,
        "userId": 98
      }, {
        "firstName": "Néhémie",
        "lastName": "Darkin",
        "email": "adarkin2q@indiatimes.com",
        "mobile": "434-598-2506",
        "address": "94752 Kings Center",
        "country": "United States",
        "city": "Charlottesville",
        "state": "Virginia",
        "zipCode": "CN-44",
        "isDefault": false,
        "userId": 99
      }, {
        "firstName": "Gérald",
        "lastName": "Crake",
        "email": "dcrake2r@barnesandnoble.com",
        "mobile": "315-759-5679",
        "address": "1500 Reindahl Road",
        "country": "United States",
        "city": "Syracuse",
        "state": "New York",
        "zipCode": "ID-PA",
        "isDefault": false,
        "userId": 100
      },
      {
        "firstName": "Crééz",
        "lastName": "Papa",
        "email": "epapa0@google.co.uk",
        "mobile": "831-985-7999",
        "address": "73 Columbus Trail",
        "country": "United States",
        "city": "Salinas",
        "state": "California",
        "zipCode": "GB-ENG",
        "isDefault": false,
        "userId": 47
      }, {
        "firstName": "Inès",
        "lastName": "Hawtin",
        "email": "chawtin1@nasa.gov",
        "mobile": "913-917-6933",
        "address": "582 Buena Vista Plaza",
        "country": "United States",
        "city": "Shawnee Mission",
        "state": "Kansas",
        "zipCode": "CO-LAG",
        "isDefault": true,
        "userId": 30
      }, {
        "firstName": "Zhì",
        "lastName": "Prenty",
        "email": "pprenty2@amazonaws.com",
        "mobile": "630-756-0796",
        "address": "0 Lunder Lane",
        "country": "United States",
        "city": "Naperville",
        "state": "Illinois",
        "zipCode": "FR-R",
        "isDefault": false,
        "userId": 44
      }, {
        "firstName": "Séverine",
        "lastName": "Gergolet",
        "email": "mgergolet3@wufoo.com",
        "mobile": "806-282-1014",
        "address": "45042 7th Court",
        "country": "United States",
        "city": "Amarillo",
        "state": "Texas",
        "zipCode": "CL-AN",
        "isDefault": true,
        "userId": 36
      }, {
        "firstName": "Eloïse",
        "lastName": "Duncanson",
        "email": "oduncanson4@cbc.ca",
        "mobile": "513-251-4772",
        "address": "25 Claremont Road",
        "country": "United States",
        "city": "Cincinnati",
        "state": "Ohio",
        "zipCode": "IL-D",
        "isDefault": false,
        "userId": 81
      }, {
        "firstName": "Léandre",
        "lastName": "Dumpleton",
        "email": "cdumpleton5@admin.ch",
        "mobile": "682-818-6046",
        "address": "4 Porter Place",
        "country": "United States",
        "city": "Fort Worth",
        "state": "Texas",
        "zipCode": "GQ-CS",
        "isDefault": true,
        "userId": 92
      }, {
        "firstName": "Maëline",
        "lastName": "Kroch",
        "email": "rkroch6@mozilla.com",
        "mobile": "414-804-7750",
        "address": "932 Helena Center",
        "country": "United States",
        "city": "Milwaukee",
        "state": "Wisconsin",
        "zipCode": "ID-JT",
        "isDefault": true,
        "userId": 51
      }, {
        "firstName": "Wá",
        "lastName": "Corter",
        "email": "mcorter7@ow.ly",
        "mobile": "901-522-1655",
        "address": "0 Talmadge Junction",
        "country": "United States",
        "city": "Memphis",
        "state": "Tennessee",
        "zipCode": "YE-MR",
        "isDefault": true,
        "userId": 63
      }, {
        "firstName": "Rachèle",
        "lastName": "Willas",
        "email": "jwillas8@alexa.com",
        "mobile": "502-437-8223",
        "address": "4327 Tomscot Road",
        "country": "United States",
        "city": "Louisville",
        "state": "Kentucky",
        "zipCode": "BR-SP",
        "isDefault": true,
        "userId": 100
      }, {
        "firstName": "Inès",
        "lastName": "MacRierie",
        "email": "pmacrierie9@dmoz.org",
        "mobile": "816-937-5922",
        "address": "885 Lyons Lane",
        "country": "United States",
        "city": "Kansas City",
        "state": "Kansas",
        "zipCode": "US-TX",
        "isDefault": false,
        "userId": 19
      }, {
        "firstName": "Félicie",
        "lastName": "Staton",
        "email": "jstatona@addtoany.com",
        "mobile": "303-828-5919",
        "address": "5 South Parkway",
        "country": "United States",
        "city": "Denver",
        "state": "Colorado",
        "zipCode": "SI-070",
        "isDefault": true,
        "userId": 79
      }, {
        "firstName": "Östen",
        "lastName": "Baldcock",
        "email": "pbaldcockb@gravatar.com",
        "mobile": "714-299-3932",
        "address": "31 Quincy Circle",
        "country": "United States",
        "city": "Garden Grove",
        "state": "California",
        "zipCode": "DZ-33",
        "isDefault": true,
        "userId": 22
      }, {
        "firstName": "Eloïse",
        "lastName": "Puckring",
        "email": "spuckringc@canalblog.com",
        "mobile": "716-463-5777",
        "address": "488 Cambridge Avenue",
        "country": "United States",
        "city": "Buffalo",
        "state": "New York",
        "zipCode": "UG-410",
        "isDefault": true,
        "userId": 11
      }, {
        "firstName": "Mylène",
        "lastName": "Cullagh",
        "email": "dcullaghd@dropbox.com",
        "mobile": "304-718-9622",
        "address": "8 Kenwood Terrace",
        "country": "United States",
        "city": "Huntington",
        "state": "West Virginia",
        "zipCode": "AU-QLD",
        "isDefault": false,
        "userId": 41
      }, {
        "firstName": "Marylène",
        "lastName": "Lyes",
        "email": "alyese@telegraph.co.uk",
        "mobile": "410-311-0665",
        "address": "62994 Kensington Center",
        "country": "United States",
        "city": "Baltimore",
        "state": "Maryland",
        "zipCode": "PA-7",
        "isDefault": false,
        "userId": 95
      }, {
        "firstName": "Noémie",
        "lastName": "Tredget",
        "email": "atredgetf@comcast.net",
        "mobile": "303-670-5551",
        "address": "888 Loomis Point",
        "country": "United States",
        "city": "Littleton",
        "state": "Colorado",
        "zipCode": "KR-41",
        "isDefault": true,
        "userId": 36
      }, {
        "firstName": "Yóu",
        "lastName": "Lowcock",
        "email": "rlowcockg@adobe.com",
        "mobile": "315-587-1713",
        "address": "0 Grover Place",
        "country": "United States",
        "city": "Syracuse",
        "state": "New York",
        "zipCode": "PG-EBR",
        "isDefault": false,
        "userId": 33
      }, {
        "firstName": "Angélique",
        "lastName": "Batkin",
        "email": "rbatkinh@nbcnews.com",
        "mobile": "718-942-0151",
        "address": "8420 American Avenue",
        "country": "United States",
        "city": "Jamaica",
        "state": "New York",
        "zipCode": "CN-65",
        "isDefault": false,
        "userId": 65
      }, {
        "firstName": "Táng",
        "lastName": "Olive",
        "email": "colivei@theglobeandmail.com",
        "mobile": "212-330-7081",
        "address": "05205 Kipling Trail",
        "country": "United States",
        "city": "New York City",
        "state": "New York",
        "zipCode": "ET-SO",
        "isDefault": false,
        "userId": 52
      }, {
        "firstName": "Renée",
        "lastName": "McKall",
        "email": "lmckallj@google.com.br",
        "mobile": "504-482-5764",
        "address": "318 Lillian Street",
        "country": "United States",
        "city": "New Orleans",
        "state": "Louisiana",
        "zipCode": "CA-BC",
        "isDefault": false,
        "userId": 7
      }, {
        "firstName": "Göran",
        "lastName": "Morkham",
        "email": "hmorkhamk@odnoklassniki.ru",
        "mobile": "717-228-3071",
        "address": "9 Amoth Road",
        "country": "United States",
        "city": "Harrisburg",
        "state": "Pennsylvania",
        "zipCode": "NL-NB",
        "isDefault": true,
        "userId": 22
      }, {
        "firstName": "Ophélie",
        "lastName": "Togwell",
        "email": "jtogwelll@bizjournals.com",
        "mobile": "412-883-4872",
        "address": "2399 Quincy Way",
        "country": "United States",
        "city": "Pittsburgh",
        "state": "Pennsylvania",
        "zipCode": "KR-46",
        "isDefault": true,
        "userId": 53
      }, {
        "firstName": "Léonore",
        "lastName": "Fosdick",
        "email": "lfosdickm@xinhuanet.com",
        "mobile": "510-867-2777",
        "address": "59569 Mccormick Parkway",
        "country": "United States",
        "city": "Berkeley",
        "state": "California",
        "zipCode": "GR-84",
        "isDefault": false,
        "userId": 93
      }, {
        "firstName": "Léone",
        "lastName": "Bullent",
        "email": "ybullentn@nbcnews.com",
        "mobile": "843-335-8870",
        "address": "82 Gulseth Point",
        "country": "United States",
        "city": "Charleston",
        "state": "South Carolina",
        "zipCode": "PK-NA",
        "isDefault": true,
        "userId": 12
      }, {
        "firstName": "Marie-françoise",
        "lastName": "Dallin",
        "email": "bdallino@guardian.co.uk",
        "mobile": "915-143-6246",
        "address": "5972 Nelson Circle",
        "country": "United States",
        "city": "El Paso",
        "state": "Texas",
        "zipCode": "ET-AF",
        "isDefault": false,
        "userId": 39
      }, {
        "firstName": "Anaël",
        "lastName": "Cobby",
        "email": "acobbyp@unicef.org",
        "mobile": "863-970-1247",
        "address": "0157 Sutherland Road",
        "country": "United States",
        "city": "Lakeland",
        "state": "Florida",
        "zipCode": "GB-ENG",
        "isDefault": false,
        "userId": 6
      }, {
        "firstName": "Maéna",
        "lastName": "Aronow",
        "email": "maronowq@theatlantic.com",
        "mobile": "513-953-5220",
        "address": "2 Shelley Junction",
        "country": "United States",
        "city": "Cincinnati",
        "state": "Ohio",
        "zipCode": "VI-U-A",
        "isDefault": false,
        "userId": 55
      }, {
        "firstName": "Méryl",
        "lastName": "Huet",
        "email": "ehuetr@instagram.com",
        "mobile": "916-116-9641",
        "address": "810 Thompson Avenue",
        "country": "United States",
        "city": "Sacramento",
        "state": "California",
        "zipCode": "US-CA",
        "isDefault": false,
        "userId": 11
      }, {
        "firstName": "Lyséa",
        "lastName": "Borrowman",
        "email": "nborrowmans@linkedin.com",
        "mobile": "915-205-6433",
        "address": "21 Pine View Hill",
        "country": "United States",
        "city": "El Paso",
        "state": "Texas",
        "zipCode": "CA-BC",
        "isDefault": false,
        "userId": 81
      }, {
        "firstName": "Françoise",
        "lastName": "Nial",
        "email": "cnialt@telegraph.co.uk",
        "mobile": "617-737-4114",
        "address": "2564 Division Pass",
        "country": "United States",
        "city": "Boston",
        "state": "Massachusetts",
        "zipCode": "IT-62",
        "isDefault": false,
        "userId": 91
      }, {
        "firstName": "Marie-thérèse",
        "lastName": "Geram",
        "email": "cgeramu@bluehost.com",
        "mobile": "432-907-8654",
        "address": "5 Montana Road",
        "country": "United States",
        "city": "Odessa",
        "state": "Texas",
        "zipCode": "ZA-NP",
        "isDefault": false,
        "userId": 19
      }, {
        "firstName": "Björn",
        "lastName": "Cloy",
        "email": "gcloyv@uiuc.edu",
        "mobile": "312-432-9673",
        "address": "38 Huxley Avenue",
        "country": "United States",
        "city": "Chicago",
        "state": "Illinois",
        "zipCode": "US-CA",
        "isDefault": true,
        "userId": 96
      }, {
        "firstName": "Bérangère",
        "lastName": "St. Pierre",
        "email": "dstpierrew@qq.com",
        "mobile": "623-627-1516",
        "address": "64 Loftsgordon Terrace",
        "country": "United States",
        "city": "Phoenix",
        "state": "Arizona",
        "zipCode": "TH-34",
        "isDefault": true,
        "userId": 58
      }, {
        "firstName": "Mà",
        "lastName": "Pinchon",
        "email": "opinchonx@posterous.com",
        "mobile": "509-826-3013",
        "address": "21015 Goodland Hill",
        "country": "United States",
        "city": "Spokane",
        "state": "Washington",
        "zipCode": "US-AK",
        "isDefault": false,
        "userId": 40
      }, {
        "firstName": "Maëlle",
        "lastName": "Rupel",
        "email": "crupely@noaa.gov",
        "mobile": "901-529-4787",
        "address": "98534 Northwestern Way",
        "country": "United States",
        "city": "Memphis",
        "state": "Tennessee",
        "zipCode": "CA-QC",
        "isDefault": true,
        "userId": 4
      }, {
        "firstName": "Rachèle",
        "lastName": "Farleigh",
        "email": "mfarleighz@wisc.edu",
        "mobile": "830-117-7405",
        "address": "7 Park Meadow Drive",
        "country": "United States",
        "city": "San Antonio",
        "state": "Texas",
        "zipCode": "AU-SA",
        "isDefault": true,
        "userId": 46
      }, {
        "firstName": "Åslög",
        "lastName": "Franschini",
        "email": "mfranschini10@free.fr",
        "mobile": "330-723-4950",
        "address": "19 John Wall Court",
        "country": "United States",
        "city": "Akron",
        "state": "Ohio",
        "zipCode": "DE-HE",
        "isDefault": false,
        "userId": 63
      }, {
        "firstName": "Séréna",
        "lastName": "Whapham",
        "email": "awhapham11@linkedin.com",
        "mobile": "305-528-6999",
        "address": "3558 Artisan Circle",
        "country": "United States",
        "city": "Miami",
        "state": "Florida",
        "zipCode": "US-WI",
        "isDefault": false,
        "userId": 66
      }, {
        "firstName": "Maéna",
        "lastName": "Inkles",
        "email": "linkles12@dion.ne.jp",
        "mobile": "304-197-6354",
        "address": "5992 Bultman Avenue",
        "country": "United States",
        "city": "Charleston",
        "state": "West Virginia",
        "zipCode": "UY-TT",
        "isDefault": true,
        "userId": 58
      }, {
        "firstName": "Célestine",
        "lastName": "Gillian",
        "email": "lgillian13@topsy.com",
        "mobile": "585-611-3513",
        "address": "70 Goodland Avenue",
        "country": "United States",
        "city": "Rochester",
        "state": "New York",
        "zipCode": "CN-65",
        "isDefault": true,
        "userId": 97
      }, {
        "firstName": "Françoise",
        "lastName": "Longland",
        "email": "elongland14@yandex.ru",
        "mobile": "504-902-2747",
        "address": "3 Oxford Trail",
        "country": "United States",
        "city": "New Orleans",
        "state": "Louisiana",
        "zipCode": "PG-CPK",
        "isDefault": false,
        "userId": 15
      }, {
        "firstName": "Måns",
        "lastName": "Warke",
        "email": "rwarke15@reference.com",
        "mobile": "603-711-8331",
        "address": "7 Brown Junction",
        "country": "United States",
        "city": "Portsmouth",
        "state": "New Hampshire",
        "zipCode": "CO-CES",
        "isDefault": true,
        "userId": 27
      }, {
        "firstName": "Jú",
        "lastName": "Dwerryhouse",
        "email": "hdwerryhouse16@spiegel.de",
        "mobile": "202-895-2025",
        "address": "39031 Meadow Vale Place",
        "country": "United States",
        "city": "Washington",
        "state": "District of Columbia",
        "zipCode": "SA-04",
        "isDefault": true,
        "userId": 46
      }, {
        "firstName": "Yú",
        "lastName": "Hollingsby",
        "email": "mhollingsby17@4shared.com",
        "mobile": "941-850-9137",
        "address": "610 Rockefeller Drive",
        "country": "United States",
        "city": "Bonita Springs",
        "state": "Florida",
        "zipCode": "AF-ORU",
        "isDefault": true,
        "userId": 12
      }, {
        "firstName": "Mégane",
        "lastName": "Clausius",
        "email": "lclausius18@nasa.gov",
        "mobile": "402-935-6964",
        "address": "5559 Sugar Pass",
        "country": "United States",
        "city": "Omaha",
        "state": "Nebraska",
        "zipCode": "BR-MG",
        "isDefault": false,
        "userId": 46
      }, {
        "firstName": "André",
        "lastName": "Clinkard",
        "email": "mclinkard19@ca.gov",
        "mobile": "901-574-3045",
        "address": "46912 Ramsey Road",
        "country": "United States",
        "city": "Memphis",
        "state": "Tennessee",
        "zipCode": "PA-8",
        "isDefault": false,
        "userId": 55
      }, {
        "firstName": "Garçon",
        "lastName": "Barszczewski",
        "email": "nbarszczewski1a@apache.org",
        "mobile": "626-163-5563",
        "address": "3 Marquette Place",
        "country": "United States",
        "city": "Corona",
        "state": "California",
        "zipCode": "IN-RJ",
        "isDefault": false,
        "userId": 92
      }, {
        "firstName": "Åsa",
        "lastName": "Gush",
        "email": "rgush1b@examiner.com",
        "mobile": "773-284-0323",
        "address": "21 Sherman Center",
        "country": "United States",
        "city": "Chicago",
        "state": "Illinois",
        "zipCode": "FR-Q",
        "isDefault": false,
        "userId": 33
      }, {
        "firstName": "Ophélie",
        "lastName": "O'Hickee",
        "email": "aohickee1c@yelp.com",
        "mobile": "513-330-8478",
        "address": "470 Clove Terrace",
        "country": "United States",
        "city": "Cincinnati",
        "state": "Ohio",
        "zipCode": "BY-MA",
        "isDefault": false,
        "userId": 39
      }, {
        "firstName": "Anaïs",
        "lastName": "Buddles",
        "email": "bbuddles1d@pcworld.com",
        "mobile": "804-628-0302",
        "address": "584 Leroy Park",
        "country": "United States",
        "city": "Richmond",
        "state": "Virginia",
        "zipCode": "SB-IS",
        "isDefault": false,
        "userId": 35
      }, {
        "firstName": "Clémentine",
        "lastName": "Halfacree",
        "email": "ehalfacree1e@google.it",
        "mobile": "804-945-8898",
        "address": "39299 Lakewood Drive",
        "country": "United States",
        "city": "Richmond",
        "state": "Virginia",
        "zipCode": "US-MI",
        "isDefault": true,
        "userId": 59
      }, {
        "firstName": "Styrbjörn",
        "lastName": "Welbrock",
        "email": "vwelbrock1f@virginia.edu",
        "mobile": "208-783-8762",
        "address": "805 Kim Crossing",
        "country": "United States",
        "city": "Portland",
        "state": "Oregon",
        "zipCode": "AU-WA",
        "isDefault": false,
        "userId": 51
      }, {
        "firstName": "Célia",
        "lastName": "Lumber",
        "email": "llumber1g@discuz.net",
        "mobile": "713-838-0157",
        "address": "30456 Summer Ridge Junction",
        "country": "United States",
        "city": "Houston",
        "state": "Texas",
        "zipCode": "CA-BC",
        "isDefault": true,
        "userId": 72
      }, {
        "firstName": "Mélina",
        "lastName": "Dracksford",
        "email": "vdracksford1h@aol.com",
        "mobile": "501-888-4794",
        "address": "00 Arizona Hill",
        "country": "United States",
        "city": "Little Rock",
        "state": "Arkansas",
        "zipCode": "YE-AD",
        "isDefault": false,
        "userId": 92
      }, {
        "firstName": "Lài",
        "lastName": "Jacobi",
        "email": "gjacobi1i@paypal.com",
        "mobile": "410-993-0415",
        "address": "1 American Ash Drive",
        "country": "United States",
        "city": "Baltimore",
        "state": "Maryland",
        "zipCode": "RU-LIP",
        "isDefault": true,
        "userId": 41
      }, {
        "firstName": "Agnès",
        "lastName": "Swindells",
        "email": "aswindells1j@homestead.com",
        "mobile": "412-543-4166",
        "address": "582 Carpenter Crossing",
        "country": "United States",
        "city": "Pittsburgh",
        "state": "Pennsylvania",
        "zipCode": "IR-03",
        "isDefault": true,
        "userId": 96
      }, {
        "firstName": "Célestine",
        "lastName": "Diviney",
        "email": "gdiviney1k@icio.us",
        "mobile": "971-338-6344",
        "address": "61 Chive Park",
        "country": "United States",
        "city": "Portland",
        "state": "Oregon",
        "zipCode": "CA-YT",
        "isDefault": true,
        "userId": 9
      }, {
        "firstName": "Cléa",
        "lastName": "Stronach",
        "email": "dstronach1l@uol.com.br",
        "mobile": "850-120-0438",
        "address": "14987 Carioca Avenue",
        "country": "United States",
        "city": "Tallahassee",
        "state": "Florida",
        "zipCode": "TR-01",
        "isDefault": false,
        "userId": 65
      }, {
        "firstName": "Irène",
        "lastName": "Cammomile",
        "email": "tcammomile1m@networkadvertising.org",
        "mobile": "316-613-6668",
        "address": "4916 Linden Alley",
        "country": "United States",
        "city": "Wichita",
        "state": "Kansas",
        "zipCode": "MY-06",
        "isDefault": true,
        "userId": 57
      }, {
        "firstName": "Adèle",
        "lastName": "Sanper",
        "email": "hsanper1n@epa.gov",
        "mobile": "205-446-2351",
        "address": "02129 Sachtjen Crossing",
        "country": "United States",
        "city": "Birmingham",
        "state": "Alabama",
        "zipCode": "US-GA",
        "isDefault": true,
        "userId": 39
      }, {
        "firstName": "Illustrée",
        "lastName": "Tickel",
        "email": "rtickel1o@google.es",
        "mobile": "626-763-9265",
        "address": "3 Melvin Hill",
        "country": "United States",
        "city": "Anaheim",
        "state": "California",
        "zipCode": "US-NV",
        "isDefault": true,
        "userId": 82
      }, {
        "firstName": "Yè",
        "lastName": "O' Quirk",
        "email": "boquirk1p@timesonline.co.uk",
        "mobile": "910-108-8814",
        "address": "96 Chinook Alley",
        "country": "United States",
        "city": "Wilmington",
        "state": "North Carolina",
        "zipCode": "BR-PR",
        "isDefault": true,
        "userId": 7
      }, {
        "firstName": "Mélodie",
        "lastName": "Wooles",
        "email": "awooles1q@spiegel.de",
        "mobile": "817-728-0465",
        "address": "9 Reindahl Street",
        "country": "United States",
        "city": "Arlington",
        "state": "Texas",
        "zipCode": "US-AL",
        "isDefault": false,
        "userId": 93
      }, {
        "firstName": "Néhémie",
        "lastName": "Burbank",
        "email": "lburbank1r@slashdot.org",
        "mobile": "316-222-8780",
        "address": "2 Graceland Trail",
        "country": "United States",
        "city": "Wichita",
        "state": "Kansas",
        "zipCode": "CA-SK",
        "isDefault": false,
        "userId": 3
      }, {
        "firstName": "Wá",
        "lastName": "Salvatore",
        "email": "csalvatore1s@washington.edu",
        "mobile": "727-337-5381",
        "address": "34 Hagan Way",
        "country": "United States",
        "city": "Saint Petersburg",
        "state": "Florida",
        "zipCode": "KZ-VOS",
        "isDefault": false,
        "userId": 54
      }, {
        "firstName": "Personnalisée",
        "lastName": "Nelthorpe",
        "email": "tnelthorpe1t@usgs.gov",
        "mobile": "772-784-2528",
        "address": "1 Morningstar Park",
        "country": "United States",
        "city": "Vero Beach",
        "state": "Florida",
        "zipCode": "PG-MPL",
        "isDefault": true,
        "userId": 26
      }, {
        "firstName": "Uò",
        "lastName": "Stobbes",
        "email": "estobbes1u@about.me",
        "mobile": "630-803-4044",
        "address": "095 Warrior Point",
        "country": "United States",
        "city": "Chicago",
        "state": "Illinois",
        "zipCode": "ID-KI",
        "isDefault": true,
        "userId": 50
      }, {
        "firstName": "Méryl",
        "lastName": "Kier",
        "email": "mkier1v@ustream.tv",
        "mobile": "817-955-1184",
        "address": "4 Hansons Junction",
        "country": "United States",
        "city": "Fort Worth",
        "state": "Texas",
        "zipCode": "US-CA",
        "isDefault": true,
        "userId": 52
      }, {
        "firstName": "Nuó",
        "lastName": "Baddeley",
        "email": "cbaddeley1w@google.com.au",
        "mobile": "727-189-6164",
        "address": "5 Golden Leaf Street",
        "country": "United States",
        "city": "Clearwater",
        "state": "Florida",
        "zipCode": "CD-KA",
        "isDefault": false,
        "userId": 72
      }, {
        "firstName": "Intéressant",
        "lastName": "Whiting",
        "email": "dwhiting1x@123-reg.co.uk",
        "mobile": "205-507-5746",
        "address": "4248 Ronald Regan Park",
        "country": "United States",
        "city": "Birmingham",
        "state": "Alabama",
        "zipCode": "CL-TA",
        "isDefault": true,
        "userId": 90
      }, {
        "firstName": "Lorène",
        "lastName": "Dixsee",
        "email": "ddixsee1y@mail.ru",
        "mobile": "520-416-4910",
        "address": "87908 Golf Course Circle",
        "country": "United States",
        "city": "Tucson",
        "state": "Arizona",
        "zipCode": "BS-NB",
        "isDefault": false,
        "userId": 91
      }, {
        "firstName": "Lèi",
        "lastName": "Punch",
        "email": "dpunch1z@webeden.co.uk",
        "mobile": "713-680-5294",
        "address": "4 Fisk Road",
        "country": "United States",
        "city": "Houston",
        "state": "Texas",
        "zipCode": "MN-073",
        "isDefault": true,
        "userId": 52
      }, {
        "firstName": "Uò",
        "lastName": "Debrick",
        "email": "hdebrick20@ucoz.com",
        "mobile": "713-611-6715",
        "address": "4665 Warbler Parkway",
        "country": "United States",
        "city": "Houston",
        "state": "Texas",
        "zipCode": "PG-MPL",
        "isDefault": true,
        "userId": 70
      }, {
        "firstName": "Sòng",
        "lastName": "Dabbs",
        "email": "cdabbs21@ebay.co.uk",
        "mobile": "682-504-2169",
        "address": "7 Meadow Vale Lane",
        "country": "United States",
        "city": "Fort Worth",
        "state": "Texas",
        "zipCode": "CA-SK",
        "isDefault": true,
        "userId": 18
      }, {
        "firstName": "Mélia",
        "lastName": "Clutterham",
        "email": "nclutterham22@gmpg.org",
        "mobile": "919-516-5580",
        "address": "29 Holy Cross Trail",
        "country": "United States",
        "city": "Raleigh",
        "state": "North Carolina",
        "zipCode": "BM-U-A",
        "isDefault": false,
        "userId": 54
      }, {
        "firstName": "Yè",
        "lastName": "Moulding",
        "email": "mmoulding23@jigsy.com",
        "mobile": "513-238-3962",
        "address": "914 Raven Street",
        "country": "United States",
        "city": "Cincinnati",
        "state": "Ohio",
        "zipCode": "GL-U-A",
        "isDefault": false,
        "userId": 36
      }, {
        "firstName": "Zhì",
        "lastName": "Lount",
        "email": "clount24@eventbrite.com",
        "mobile": "559-918-8426",
        "address": "978 Pleasure Park",
        "country": "United States",
        "city": "Fresno",
        "state": "California",
        "zipCode": "US-WI",
        "isDefault": false,
        "userId": 50
      }, {
        "firstName": "Hélène",
        "lastName": "Opdenort",
        "email": "lopdenort25@twitpic.com",
        "mobile": "425-274-8336",
        "address": "686 Steensland Terrace",
        "country": "United States",
        "city": "Everett",
        "state": "Washington",
        "zipCode": "LK-5",
        "isDefault": true,
        "userId": 94
      }, {
        "firstName": "Eléonore",
        "lastName": "Woolaghan",
        "email": "jwoolaghan26@unblog.fr",
        "mobile": "213-588-8673",
        "address": "50771 Victoria Alley",
        "country": "United States",
        "city": "Los Angeles",
        "state": "California",
        "zipCode": "HT-GA",
        "isDefault": false,
        "userId": 83
      }, {
        "firstName": "Océane",
        "lastName": "Relton",
        "email": "rrelton27@nationalgeographic.com",
        "mobile": "202-355-8160",
        "address": "8857 Haas Center",
        "country": "United States",
        "city": "Washington",
        "state": "District of Columbia",
        "zipCode": "US-AZ",
        "isDefault": false,
        "userId": 48
      }, {
        "firstName": "Geneviève",
        "lastName": "Faragan",
        "email": "hfaragan28@ftc.gov",
        "mobile": "240-510-9839",
        "address": "57497 Schurz Street",
        "country": "United States",
        "city": "Frederick",
        "state": "Maryland",
        "zipCode": "NA-KA",
        "isDefault": true,
        "userId": 17
      }, {
        "firstName": "Mélissandre",
        "lastName": "Brydon",
        "email": "lbrydon29@vk.com",
        "mobile": "651-228-4708",
        "address": "4170 Clarendon Lane",
        "country": "United States",
        "city": "Minneapolis",
        "state": "Minnesota",
        "zipCode": "US-KY",
        "isDefault": true,
        "userId": 20
      }, {
        "firstName": "Stéphanie",
        "lastName": "Redbourn",
        "email": "rredbourn2a@amazon.co.uk",
        "mobile": "903-756-9800",
        "address": "8076 South Circle",
        "country": "United States",
        "city": "Tyler",
        "state": "Texas",
        "zipCode": "IS-7",
        "isDefault": false,
        "userId": 39
      }, {
        "firstName": "Angélique",
        "lastName": "Marron",
        "email": "nmarron2b@wikia.com",
        "mobile": "-760-9207",
        "address": "717 Thompson Hill",
        "country": "United States",
        "city": "Pittsburgh",
        "state": "Pennsylvania",
        "zipCode": "PG-NPP",
        "isDefault": false,
        "userId": 29
      }, {
        "firstName": "Réjane",
        "lastName": "Oxborrow",
        "email": "loxborrow2c@topsy.com",
        "mobile": "214-461-1572",
        "address": "68 Hallows Junction",
        "country": "United States",
        "city": "Dallas",
        "state": "Texas",
        "zipCode": "FR-D",
        "isDefault": false,
        "userId": 59
      }, {
        "firstName": "Åslög",
        "lastName": "Mc Combe",
        "email": "cmccombe2d@npr.org",
        "mobile": "510-604-3044",
        "address": "69010 Amoth Way",
        "country": "United States",
        "city": "Oakland",
        "state": "California",
        "zipCode": "PH-DAV",
        "isDefault": true,
        "userId": 76
      }, {
        "firstName": "Célestine",
        "lastName": "Pasley",
        "email": "kpasley2e@reuters.com",
        "mobile": "314-767-0351",
        "address": "7089 Burning Wood Point",
        "country": "United States",
        "city": "Saint Louis",
        "state": "Missouri",
        "zipCode": "BR-SP",
        "isDefault": true,
        "userId": 90
      }, {
        "firstName": "Naéva",
        "lastName": "Tyne",
        "email": "rtyne2f@google.com.br",
        "mobile": "205-588-6296",
        "address": "77570 Caliangt Court",
        "country": "United States",
        "city": "Birmingham",
        "state": "Alabama",
        "zipCode": "AU-QLD",
        "isDefault": true,
        "userId": 35
      }, {
        "firstName": "Sélène",
        "lastName": "De Goey",
        "email": "zdegoey2g@plala.or.jp",
        "mobile": "916-740-0302",
        "address": "289 Milwaukee Street",
        "country": "United States",
        "city": "Sacramento",
        "state": "California",
        "zipCode": "US-MT",
        "isDefault": true,
        "userId": 73
      }, {
        "firstName": "Åke",
        "lastName": "Salmond",
        "email": "dsalmond2h@ft.com",
        "mobile": "510-508-8216",
        "address": "32 Northland Avenue",
        "country": "United States",
        "city": "Irvine",
        "state": "California",
        "zipCode": "CA-ON",
        "isDefault": true,
        "userId": 99
      }, {
        "firstName": "Daphnée",
        "lastName": "Reeday",
        "email": "treeday2i@virginia.edu",
        "mobile": "570-833-9130",
        "address": "11 Fremont Plaza",
        "country": "United States",
        "city": "Wilkes Barre",
        "state": "Pennsylvania",
        "zipCode": "IT-62",
        "isDefault": true,
        "userId": 20
      }, {
        "firstName": "Intéressant",
        "lastName": "Hallede",
        "email": "ahallede2j@cocolog-nifty.com",
        "mobile": "915-181-6959",
        "address": "2066 Messerschmidt Plaza",
        "country": "United States",
        "city": "El Paso",
        "state": "Texas",
        "zipCode": "US-FL",
        "isDefault": true,
        "userId": 24
      }, {
        "firstName": "Håkan",
        "lastName": "McAteer",
        "email": "nmcateer2k@goo.gl",
        "mobile": "339-794-8410",
        "address": "07 Elmside Junction",
        "country": "United States",
        "city": "Boston",
        "state": "Massachusetts",
        "zipCode": "TC-GT",
        "isDefault": true,
        "userId": 61
      }, {
        "firstName": "Camélia",
        "lastName": "Ghioni",
        "email": "tghioni2l@apple.com",
        "mobile": "970-486-7512",
        "address": "026 Larry Park",
        "country": "United States",
        "city": "Fort Collins",
        "state": "Colorado",
        "zipCode": "ET-GA",
        "isDefault": false,
        "userId": 46
      }, {
        "firstName": "Maëlann",
        "lastName": "Hekkert",
        "email": "phekkert2m@jiathis.com",
        "mobile": "218-815-2680",
        "address": "686 Spaight Avenue",
        "country": "United States",
        "city": "Duluth",
        "state": "Minnesota",
        "zipCode": "CN-15",
        "isDefault": false,
        "userId": 88
      }, {
        "firstName": "Méng",
        "lastName": "Kundert",
        "email": "akundert2n@a8.net",
        "mobile": "718-909-6796",
        "address": "33 Northland Terrace",
        "country": "United States",
        "city": "Bronx",
        "state": "New York",
        "zipCode": "AU-SA",
        "isDefault": true,
        "userId": 47
      }, {
        "firstName": "Dorothée",
        "lastName": "Burds",
        "email": "tburds2o@webmd.com",
        "mobile": "619-463-9565",
        "address": "43 Fairview Trail",
        "country": "United States",
        "city": "San Diego",
        "state": "California",
        "zipCode": "PG-MPL",
        "isDefault": false,
        "userId": 98
      }, {
        "firstName": "Måns",
        "lastName": "Cawcutt",
        "email": "ecawcutt2p@lycos.com",
        "mobile": "209-195-5022",
        "address": "1 Sunfield Parkway",
        "country": "United States",
        "city": "Hayward",
        "state": "California",
        "zipCode": "CN-45",
        "isDefault": false,
        "userId": 27
      }, {
        "firstName": "Anaé",
        "lastName": "Mounsie",
        "email": "lmounsie2q@reddit.com",
        "mobile": "815-339-6166",
        "address": "090 Laurel Avenue",
        "country": "United States",
        "city": "Joliet",
        "state": "Illinois",
        "zipCode": "AU-NT",
        "isDefault": false,
        "userId": 87
      }, {
        "firstName": "Gaïa",
        "lastName": "Kunzel",
        "email": "lkunzel2r@wikipedia.org",
        "mobile": "530-804-8455",
        "address": "9006 Towne Lane",
        "country": "United States",
        "city": "Sacramento",
        "state": "California",
        "zipCode": "ID-MA",
        "isDefault": false,
        "userId": 90
      }
    ];

    items.forEach((item) => {
      item.createdAt = Sequelize.literal("NOW()");
      item.updatedAt = Sequelize.literal("NOW()");
    });
    await queryInterface.bulkInsert("Addresses", items, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Addresses", null, {});
  },
};
