'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        const items = [{
            "email": "ssoeiro0@examiner.com",
            "password": "z7wlt7AS",
            "firstName": "Stacee",
            "lastName": "Soeiro",
            "mobile": "184-207-4315"
          }, {
            "email": "mcuckson1@dropbox.com",
            "password": "5pRs5c",
            "firstName": "Mendie",
            "lastName": "Cuckson",
            "mobile": "853-743-7816"
          }, {
            "email": "slehenmann2@chronoengine.com",
            "password": "LqjB9c5YB",
            "firstName": "Simone",
            "lastName": "Lehenmann",
            "mobile": "975-703-5466"
          }, {
            "email": "pliquorish3@webnode.com",
            "password": "yLsMKznILdwx",
            "firstName": "Pippo",
            "lastName": "Liquorish",
            "mobile": "886-522-5059"
          }, {
            "email": "aneagle4@soup.io",
            "password": "D28d5imjg",
            "firstName": "Arthur",
            "lastName": "Neagle",
            "mobile": "981-360-2349"
          }, {
            "email": "mbachs5@blog.com",
            "password": "tRdfXO",
            "firstName": "Morton",
            "lastName": "Bachs",
            "mobile": "893-964-5481"
          }, {
            "email": "harnatt6@bravesites.com",
            "password": "2HiTGvLVL",
            "firstName": "Horton",
            "lastName": "Arnatt",
            "mobile": "360-515-3313"
          }, {
            "email": "blestrange7@studiopress.com",
            "password": "ri2oxjJ53bsg",
            "firstName": "Beck",
            "lastName": "Le Strange",
            "mobile": "118-333-5367"
          }, {
            "email": "epattingson8@paypal.com",
            "password": "mBlg90d",
            "firstName": "Errol",
            "lastName": "Pattingson",
            "mobile": "445-902-8053"
          }, {
            "email": "epietruszka9@opensource.org",
            "password": "FfqEO5ad8TL",
            "firstName": "Earl",
            "lastName": "Pietruszka",
            "mobile": "137-864-4906"
          }, {
            "email": "storrea@google.pl",
            "password": "glw7OS",
            "firstName": "Saleem",
            "lastName": "Torre",
            "mobile": "670-247-9725"
          }, {
            "email": "morrocksb@canalblog.com",
            "password": "6cWSV5v",
            "firstName": "Matty",
            "lastName": "Orrocks",
            "mobile": "682-698-8579"
          }, {
            "email": "kosheec@bloomberg.com",
            "password": "eOtKr3Tz4",
            "firstName": "Kleon",
            "lastName": "O'Shee",
            "mobile": "529-231-7106"
          }, {
            "email": "hnevittd@live.com",
            "password": "kQfHSZQMnR",
            "firstName": "Horacio",
            "lastName": "Nevitt",
            "mobile": "968-992-1849"
          }, {
            "email": "echimentie@storify.com",
            "password": "VpduH9NPL",
            "firstName": "Ervin",
            "lastName": "Chimenti",
            "mobile": "945-823-3878"
          }, {
            "email": "wbraunleinf@gizmodo.com",
            "password": "tlZuhJ0OYzWR",
            "firstName": "Waylan",
            "lastName": "Braunlein",
            "mobile": "141-700-7337"
          }, {
            "email": "imanueaug@reuters.com",
            "password": "2vNv1TLBN1KV",
            "firstName": "Ingelbert",
            "lastName": "Manueau",
            "mobile": "393-700-9614"
          }, {
            "email": "dpotellh@google.fr",
            "password": "dJ6Kurw1r",
            "firstName": "Donnell",
            "lastName": "Potell",
            "mobile": "429-550-8888"
          }, {
            "email": "smaylouri@shinystat.com",
            "password": "HXssuu",
            "firstName": "Salem",
            "lastName": "Maylour",
            "mobile": "678-840-2926"
          }, {
            "email": "eiaduccellij@homestead.com",
            "password": "k5vHtqrBkl",
            "firstName": "Evered",
            "lastName": "Iaduccelli",
            "mobile": "614-451-7714"
          }, {
            "email": "ebrotherickk@uol.com.br",
            "password": "4t41wcluzN",
            "firstName": "Em",
            "lastName": "Brotherick",
            "mobile": "556-944-8956"
          }, {
            "email": "kstigerl@yale.edu",
            "password": "hR9nuYG",
            "firstName": "Kristopher",
            "lastName": "Stiger",
            "mobile": "640-312-3404"
          }, {
            "email": "dferrettinim@state.gov",
            "password": "pwtEOyZj",
            "firstName": "Dion",
            "lastName": "Ferrettini",
            "mobile": "932-639-8335"
          }, {
            "email": "akhidrn@dailymail.co.uk",
            "password": "aWd4st",
            "firstName": "Allan",
            "lastName": "Khidr",
            "mobile": "450-768-9932"
          }, {
            "email": "broskamo@hibu.com",
            "password": "CvausX52s",
            "firstName": "Bucky",
            "lastName": "Roskam",
            "mobile": "963-775-8732"
          }, {
            "email": "spledgerp@craigslist.org",
            "password": "1vgSDl2",
            "firstName": "Schuyler",
            "lastName": "Pledger",
            "mobile": "289-502-4002"
          }, {
            "email": "fkulisq@about.me",
            "password": "FJ7dsz",
            "firstName": "Felicio",
            "lastName": "Kulis",
            "mobile": "492-598-6914"
          }, {
            "email": "dlemmr@comsenz.com",
            "password": "qBwdaav",
            "firstName": "Danny",
            "lastName": "Lemm",
            "mobile": "830-875-7248"
          }, {
            "email": "hmounters@dyndns.org",
            "password": "bi5Tlb9E",
            "firstName": "Haze",
            "lastName": "Mounter",
            "mobile": "145-419-6679"
          }, {
            "email": "sspallt@ihg.com",
            "password": "4o1laKxBSZ",
            "firstName": "Stanford",
            "lastName": "Spall",
            "mobile": "551-254-7620"
          }, {
            "email": "ugougeu@vk.com",
            "password": "uksM0NV0z",
            "firstName": "Urban",
            "lastName": "Gouge",
            "mobile": "644-577-8328"
          }, {
            "email": "mewensonv@php.net",
            "password": "sJ8sG9sQRl",
            "firstName": "Mack",
            "lastName": "Ewenson",
            "mobile": "273-373-5114"
          }, {
            "email": "bmcgirrw@shareasale.com",
            "password": "cYgSRUD60I",
            "firstName": "Brit",
            "lastName": "McGirr",
            "mobile": "687-749-1968"
          }, {
            "email": "vgarricx@netlog.com",
            "password": "Spuyyd",
            "firstName": "Vincenz",
            "lastName": "Garric",
            "mobile": "866-119-8913"
          }, {
            "email": "rdalzielly@mediafire.com",
            "password": "3vGIlRSLreK",
            "firstName": "Rhys",
            "lastName": "Dalziell",
            "mobile": "278-734-5273"
          }, {
            "email": "ehellerz@topsy.com",
            "password": "6egjHFlOzeB",
            "firstName": "Elmo",
            "lastName": "Heller",
            "mobile": "294-692-5863"
          }, {
            "email": "ajakeman10@senate.gov",
            "password": "bRcNEI2hv6",
            "firstName": "Agustin",
            "lastName": "Jakeman",
            "mobile": "124-127-7129"
          }, {
            "email": "bdarnbrough11@bloglovin.com",
            "password": "kgxNmMtwcre",
            "firstName": "Berk",
            "lastName": "Darnbrough",
            "mobile": "115-552-9693"
          }, {
            "email": "crangeley12@phpbb.com",
            "password": "ZT4RYW",
            "firstName": "Cyrillus",
            "lastName": "Rangeley",
            "mobile": "220-530-8630"
          }, {
            "email": "cmaidment13@mysql.com",
            "password": "PeNbY1Y",
            "firstName": "Chev",
            "lastName": "Maidment",
            "mobile": "172-645-1575"
          }, {
            "email": "gscarasbrick14@merriam-webster.com",
            "password": "l8fuVeHgDgX",
            "firstName": "Giffer",
            "lastName": "Scarasbrick",
            "mobile": "655-743-7573"
          }, {
            "email": "tbock15@nps.gov",
            "password": "9lcIoD5OoW",
            "firstName": "Tedman",
            "lastName": "Bock",
            "mobile": "175-963-2196"
          }, {
            "email": "bmitchard16@shareasale.com",
            "password": "6ZI3EOhGmG",
            "firstName": "Brod",
            "lastName": "Mitchard",
            "mobile": "612-460-9591"
          }, {
            "email": "ewoodyear17@bravesites.com",
            "password": "jjoqA2n8Il",
            "firstName": "Ewan",
            "lastName": "Woodyear",
            "mobile": "165-377-5802"
          }, {
            "email": "jstainbridge18@ehow.com",
            "password": "rZCHdshR",
            "firstName": "Jayme",
            "lastName": "Stainbridge",
            "mobile": "356-480-8619"
          }, {
            "email": "ahoyt19@google.es",
            "password": "UXFPzsrylxi4",
            "firstName": "Artemus",
            "lastName": "Hoyt",
            "mobile": "342-182-7198"
          }, {
            "email": "dsterling1a@prnewswire.com",
            "password": "4GuZ4T9Md",
            "firstName": "Don",
            "lastName": "Sterling",
            "mobile": "192-701-6064"
          }, {
            "email": "preolfi1b@yolasite.com",
            "password": "v412VafjE4",
            "firstName": "Peirce",
            "lastName": "Reolfi",
            "mobile": "895-190-8081"
          }, {
            "email": "inertney1c@about.me",
            "password": "2OfOpU4GT",
            "firstName": "Immanuel",
            "lastName": "Nertney",
            "mobile": "663-209-7853"
          }, {
            "email": "fcrippell1d@chronoengine.com",
            "password": "mQl4mkU0sL",
            "firstName": "Frans",
            "lastName": "Crippell",
            "mobile": "963-102-8537"
          }, {
            "email": "idocket1e@paginegialle.it",
            "password": "kR6AlADGW",
            "firstName": "Ira",
            "lastName": "Docket",
            "mobile": "649-679-3644"
          }, {
            "email": "hlarmour1f@last.fm",
            "password": "pE9EVH0OB",
            "firstName": "Horst",
            "lastName": "Larmour",
            "mobile": "763-636-9781"
          }, {
            "email": "aklais1g@blog.com",
            "password": "Qa2VyedpD5Ik",
            "firstName": "Archy",
            "lastName": "Klais",
            "mobile": "977-350-5436"
          }, {
            "email": "rwhitnell1h@independent.co.uk",
            "password": "OI1t7bZ7kgIw",
            "firstName": "Royce",
            "lastName": "Whitnell",
            "mobile": "731-198-1207"
          }, {
            "email": "hplank1i@angelfire.com",
            "password": "V2saHTtX",
            "firstName": "Humfrid",
            "lastName": "Plank",
            "mobile": "522-225-9542"
          }, {
            "email": "cgumb1j@ox.ac.uk",
            "password": "VluEtxLdccc",
            "firstName": "Chandler",
            "lastName": "Gumb",
            "mobile": "377-885-5687"
          }, {
            "email": "hpaffot1k@netscape.com",
            "password": "CNmHt6OM",
            "firstName": "Haily",
            "lastName": "Paffot",
            "mobile": "979-439-1639"
          }, {
            "email": "ndenyagin1l@yellowbook.com",
            "password": "T29fy4Dhm0",
            "firstName": "Neill",
            "lastName": "Denyagin",
            "mobile": "728-778-5780"
          }, {
            "email": "gmccoughan1m@harvard.edu",
            "password": "rez0v0DWjlqB",
            "firstName": "Guthrie",
            "lastName": "Mc Coughan",
            "mobile": "609-228-4876"
          }, {
            "email": "uhindrich1n@google.co.jp",
            "password": "XBubCjN",
            "firstName": "Udell",
            "lastName": "Hindrich",
            "mobile": "997-562-1372"
          }, {
            "email": "mholworth1o@t.co",
            "password": "nIHGdF1x2imD",
            "firstName": "Merrick",
            "lastName": "Holworth",
            "mobile": "575-724-2380"
          }, {
            "email": "drossiter1p@msu.edu",
            "password": "HO4XDlDx",
            "firstName": "Derrek",
            "lastName": "Rossiter",
            "mobile": "108-136-3875"
          }, {
            "email": "gstokey1q@over-blog.com",
            "password": "EfO7qd",
            "firstName": "Granville",
            "lastName": "Stokey",
            "mobile": "124-545-5185"
          }, {
            "email": "mfransseni1r@icq.com",
            "password": "BxesAvUpGkI1",
            "firstName": "Morgan",
            "lastName": "Fransseni",
            "mobile": "966-982-6827"
          }, {
            "email": "sferriday1s@cornell.edu",
            "password": "P8Lr7Ng6USnN",
            "firstName": "Sayer",
            "lastName": "Ferriday",
            "mobile": "177-756-8677"
          }, {
            "email": "prannald1t@nih.gov",
            "password": "SJ1C4PFXmEOb",
            "firstName": "Peirce",
            "lastName": "Rannald",
            "mobile": "140-757-6614"
          }, {
            "email": "lgooders1u@hhs.gov",
            "password": "ZSIroPQ",
            "firstName": "Lev",
            "lastName": "Gooders",
            "mobile": "632-763-6726"
          }, {
            "email": "sgoodram1v@indiatimes.com",
            "password": "K4i96v",
            "firstName": "Stanley",
            "lastName": "Goodram",
            "mobile": "329-240-8060"
          }, {
            "email": "rtickner1w@jigsy.com",
            "password": "7lhuJnsWNm",
            "firstName": "Rinaldo",
            "lastName": "Tickner",
            "mobile": "753-879-4412"
          }, {
            "email": "swestney1x@nyu.edu",
            "password": "j5oSgnS",
            "firstName": "Sunny",
            "lastName": "Westney",
            "mobile": "594-798-7738"
          }, {
            "email": "shalsall1y@odnoklassniki.ru",
            "password": "dV8FwKlK",
            "firstName": "Saxon",
            "lastName": "Halsall",
            "mobile": "552-602-2049"
          }, {
            "email": "ukleinstern1z@canalblog.com",
            "password": "CRsOLV",
            "firstName": "Urban",
            "lastName": "Kleinstern",
            "mobile": "177-893-5522"
          }, {
            "email": "rtitta20@wikispaces.com",
            "password": "TorHNYrJ8RQ8",
            "firstName": "Raviv",
            "lastName": "Titta",
            "mobile": "453-206-1232"
          }, {
            "email": "cglascott21@census.gov",
            "password": "nXAZzPCiS",
            "firstName": "Curran",
            "lastName": "Glascott",
            "mobile": "828-708-5344"
          }, {
            "email": "aledwith22@rediff.com",
            "password": "6srjVZ",
            "firstName": "Ashton",
            "lastName": "Ledwith",
            "mobile": "109-685-2610"
          }, {
            "email": "rmcgirr23@cloudflare.com",
            "password": "eiZDrKWpp",
            "firstName": "Randal",
            "lastName": "McGirr",
            "mobile": "320-888-1076"
          }, {
            "email": "kdowsey24@mlb.com",
            "password": "AcZy8xWqMH",
            "firstName": "Kiley",
            "lastName": "Dowsey",
            "mobile": "351-366-2127"
          }, {
            "email": "eweddeburn25@techcrunch.com",
            "password": "IgDsi3XJC8",
            "firstName": "Ephraim",
            "lastName": "Weddeburn",
            "mobile": "132-956-7421"
          }, {
            "email": "gcivitillo26@slashdot.org",
            "password": "WAVByCKwiTn",
            "firstName": "Gib",
            "lastName": "Civitillo",
            "mobile": "440-336-9720"
          }, {
            "email": "aconner27@nps.gov",
            "password": "BcdnsLc",
            "firstName": "Antonin",
            "lastName": "Conner",
            "mobile": "977-421-6421"
          }, {
            "email": "rtarbin28@dyndns.org",
            "password": "KPffxu",
            "firstName": "Ricki",
            "lastName": "Tarbin",
            "mobile": "638-506-3465"
          }, {
            "email": "cstiller29@weebly.com",
            "password": "suoo5l",
            "firstName": "Charlton",
            "lastName": "Stiller",
            "mobile": "887-419-8186"
          }, {
            "email": "sposselow2a@purevolume.com",
            "password": "K6rBa6dq8An",
            "firstName": "Shep",
            "lastName": "Posselow",
            "mobile": "970-640-5098"
          }, {
            "email": "gliversage2b@house.gov",
            "password": "U8j4gK",
            "firstName": "Gideon",
            "lastName": "Liversage",
            "mobile": "439-532-4807"
          }, {
            "email": "fcopozio2c@twitter.com",
            "password": "VGedeBWFEK9",
            "firstName": "Foster",
            "lastName": "Copozio",
            "mobile": "191-267-5388"
          }, {
            "email": "agowenlock2d@wired.com",
            "password": "KzRLDvgg",
            "firstName": "Aluino",
            "lastName": "Gowenlock",
            "mobile": "689-955-4182"
          }, {
            "email": "odeangelis2e@uiuc.edu",
            "password": "zIoSbLO",
            "firstName": "Otis",
            "lastName": "De Angelis",
            "mobile": "651-796-8525"
          }, {
            "email": "shasling2f@ihg.com",
            "password": "39XEHX",
            "firstName": "Spencer",
            "lastName": "Hasling",
            "mobile": "565-875-3424"
          }, {
            "email": "bwait2g@kickstarter.com",
            "password": "R92EYCX",
            "firstName": "Bartholomew",
            "lastName": "Wait",
            "mobile": "337-564-8719"
          }, {
            "email": "rminget2h@wufoo.com",
            "password": "fMSR2IuS6fCX",
            "firstName": "Randolph",
            "lastName": "Minget",
            "mobile": "532-184-3446"
          }, {
            "email": "fkeming2i@tinyurl.com",
            "password": "JEiVFAfZ5B1j",
            "firstName": "Finn",
            "lastName": "Keming",
            "mobile": "763-735-5481"
          }, {
            "email": "vcanti2j@google.cn",
            "password": "ElnbrWJPQ5",
            "firstName": "Vergil",
            "lastName": "Canti",
            "mobile": "587-638-7266"
          }, {
            "email": "ckemmons2k@rakuten.co.jp",
            "password": "oW7K5zOhjGOC",
            "firstName": "Colin",
            "lastName": "Kemmons",
            "mobile": "467-695-6610"
          }, {
            "email": "arudeyeard2l@hud.gov",
            "password": "Lvazs3vd3lAo",
            "firstName": "Augustin",
            "lastName": "Rudeyeard",
            "mobile": "808-386-4098"
          }, {
            "email": "wbramwich2m@usda.gov",
            "password": "DSylCGxnM5p",
            "firstName": "Wyn",
            "lastName": "Bramwich",
            "mobile": "259-179-4729"
          }, {
            "email": "ktattersdill2n@infoseek.co.jp",
            "password": "yjoEOuaq",
            "firstName": "Karlis",
            "lastName": "Tattersdill",
            "mobile": "183-406-1418"
          }, {
            "email": "mfosdike2o@w3.org",
            "password": "TNZkUCp",
            "firstName": "Marlin",
            "lastName": "Fosdike",
            "mobile": "619-293-5347"
          }, {
            "email": "rlatan2p@wikimedia.org",
            "password": "XWpkFPT4GO",
            "firstName": "Roderich",
            "lastName": "Latan",
            "mobile": "853-976-1895"
          }, {
            "email": "smcgaffey2q@spiegel.de",
            "password": "zXq5YlFfaZoo",
            "firstName": "Steward",
            "lastName": "McGaffey",
            "mobile": "203-110-2116"
          }, {
            "email": "wnursey2r@mayoclinic.com",
            "password": "cpgAIInEd",
            "firstName": "Weidar",
            "lastName": "Nursey",
            "mobile": "310-522-1691"
          },
          {
            "email": "sluxton0@time.com",
            "password": "dAuwhuMkpUAL",
            "firstName": "Estée",
            "lastName": "Luxton",
            "mobile": "328-541-8197"
          }, {
            "email": "mrobillart1@msn.com",
            "password": "XbFRMmKVn",
            "firstName": "Gaétane",
            "lastName": "Robillart",
            "mobile": "312-957-7685"
          }, {
            "email": "pmerriott2@symantec.com",
            "password": "v7blRKYF",
            "firstName": "Maïlys",
            "lastName": "Merriott",
            "mobile": "797-376-9252"
          }, {
            "email": "cpeacock3@furl.net",
            "password": "y1bnA8J2NGuI",
            "firstName": "Léa",
            "lastName": "Peacock",
            "mobile": "779-612-7708"
          }, {
            "email": "khudson4@a8.net",
            "password": "Y0g8a1",
            "firstName": "Eléa",
            "lastName": "Hudson",
            "mobile": "159-314-7044"
          }, {
            "email": "sshanklin5@bigcartel.com",
            "password": "C46w66",
            "firstName": "Dafnée",
            "lastName": "Shanklin",
            "mobile": "325-603-4477"
          }, {
            "email": "tdilkes6@imgur.com",
            "password": "4lsvS8puzo",
            "firstName": "Clélia",
            "lastName": "Dilkes",
            "mobile": "287-759-3622"
          }, {
            "email": "zsawford7@shutterfly.com",
            "password": "T3CcaAeg",
            "firstName": "Sélène",
            "lastName": "Sawford",
            "mobile": "180-458-2185"
          }, {
            "email": "kgioan8@51.la",
            "password": "gCX8bncvLQXB",
            "firstName": "Séréna",
            "lastName": "Gioan",
            "mobile": "685-144-5234"
          }, {
            "email": "kbisp9@amazonaws.com",
            "password": "HpaIgK",
            "firstName": "Célia",
            "lastName": "Bisp",
            "mobile": "620-890-1414"
          }, {
            "email": "tmeekinga@bloglovin.com",
            "password": "yUeeSD5GOs",
            "firstName": "Maïlis",
            "lastName": "Meeking",
            "mobile": "102-761-5289"
          }, {
            "email": "ddaccab@washingtonpost.com",
            "password": "emgtflqkE",
            "firstName": "Véronique",
            "lastName": "Dacca",
            "mobile": "392-742-5733"
          }, {
            "email": "ehaddyc@php.net",
            "password": "MapH9vo",
            "firstName": "Médiamass",
            "lastName": "Haddy",
            "mobile": "620-707-6318"
          }, {
            "email": "yfehelyd@google.com.hk",
            "password": "9VMdz7nb",
            "firstName": "Uò",
            "lastName": "Fehely",
            "mobile": "204-153-8574"
          }, {
            "email": "hingolde@ox.ac.uk",
            "password": "d7DsOxao",
            "firstName": "Mårten",
            "lastName": "Ingold",
            "mobile": "593-303-6972"
          }, {
            "email": "jcullingworthf@creativecommons.org",
            "password": "unDsLKZ",
            "firstName": "Inès",
            "lastName": "Cullingworth",
            "mobile": "967-679-7470"
          }, {
            "email": "cjobeyg@whitehouse.gov",
            "password": "qdH4WTl",
            "firstName": "Bénédicte",
            "lastName": "Jobey",
            "mobile": "949-652-1833"
          }, {
            "email": "valimanh@wordpress.org",
            "password": "L89CnwZv",
            "firstName": "Maëlla",
            "lastName": "Aliman",
            "mobile": "442-101-3451"
          }, {
            "email": "kloffeli@digg.com",
            "password": "D8uQGuG1owU",
            "firstName": "Eléonore",
            "lastName": "Loffel",
            "mobile": "111-388-6301"
          }, {
            "email": "dmcilhaggaj@oracle.com",
            "password": "QT29zibN5",
            "firstName": "Marie-josée",
            "lastName": "McIlhagga",
            "mobile": "109-345-6424"
          }, {
            "email": "ababbsk@engadget.com",
            "password": "nlxBicYaLUx",
            "firstName": "Camélia",
            "lastName": "Babbs",
            "mobile": "444-582-4272"
          }, {
            "email": "amclorinanl@e-recht24.de",
            "password": "riuK5m",
            "firstName": "Fèi",
            "lastName": "McLorinan",
            "mobile": "545-293-5178"
          }, {
            "email": "tbottrellm@indiatimes.com",
            "password": "2QSxythzA",
            "firstName": "Danièle",
            "lastName": "Bottrell",
            "mobile": "619-437-2546"
          }, {
            "email": "scasonen@ameblo.jp",
            "password": "gNlQcxrR",
            "firstName": "Félicie",
            "lastName": "Casone",
            "mobile": "468-478-2833"
          }, {
            "email": "amechico@yolasite.com",
            "password": "6rRmtagpMKM",
            "firstName": "Naéva",
            "lastName": "Mechic",
            "mobile": "261-770-7430"
          }, {
            "email": "vroelvinkp@fotki.com",
            "password": "odsEYX",
            "firstName": "Bécassine",
            "lastName": "Roelvink",
            "mobile": "261-882-6564"
          }, {
            "email": "jniavesq@google.fr",
            "password": "8DPwOgtss",
            "firstName": "Solène",
            "lastName": "Niaves",
            "mobile": "611-857-3411"
          }, {
            "email": "djanawayr@google.pl",
            "password": "oOoCVtOOxv5",
            "firstName": "Bérengère",
            "lastName": "Janaway",
            "mobile": "120-796-4688"
          }, {
            "email": "cvenneys@time.com",
            "password": "DlmaFQ0kbFx",
            "firstName": "Véronique",
            "lastName": "Venney",
            "mobile": "328-879-2598"
          }, {
            "email": "hmerrickt@tinypic.com",
            "password": "B6BIw5sd3lJ9",
            "firstName": "Håkan",
            "lastName": "Merrick",
            "mobile": "160-104-3944"
          }, {
            "email": "rsiggersu@newsvine.com",
            "password": "M20LOoTk9",
            "firstName": "Adélaïde",
            "lastName": "Siggers",
            "mobile": "358-638-7096"
          }, {
            "email": "rmckelveyv@creativecommons.org",
            "password": "2u1f53",
            "firstName": "Danièle",
            "lastName": "McKelvey",
            "mobile": "972-604-7521"
          }, {
            "email": "klutherw@vinaora.com",
            "password": "3pomrJWqvX",
            "firstName": "Örjan",
            "lastName": "Luther",
            "mobile": "891-176-9358"
          }, {
            "email": "kjoanaudx@google.nl",
            "password": "0NmtVFjzXA",
            "firstName": "Stévina",
            "lastName": "Joanaud",
            "mobile": "739-244-6405"
          }, {
            "email": "kwillimoty@apple.com",
            "password": "f0hdipQ9B0vg",
            "firstName": "Börje",
            "lastName": "Willimot",
            "mobile": "704-752-5270"
          }, {
            "email": "sstonez@geocities.jp",
            "password": "9e1P2lqo",
            "firstName": "Vénus",
            "lastName": "Stone",
            "mobile": "258-884-3899"
          }, {
            "email": "elefever10@globo.com",
            "password": "mrRbed47wW",
            "firstName": "Yè",
            "lastName": "Lefever",
            "mobile": "712-711-6345"
          }, {
            "email": "lbierman11@furl.net",
            "password": "bgMS6w2",
            "firstName": "Gösta",
            "lastName": "Bierman",
            "mobile": "879-600-5194"
          }, {
            "email": "hcolicot12@ocn.ne.jp",
            "password": "Et26fcojsjze",
            "firstName": "Michèle",
            "lastName": "Colicot",
            "mobile": "712-807-9609"
          }, {
            "email": "egresch13@china.com.cn",
            "password": "QMEeOCk",
            "firstName": "Léana",
            "lastName": "Gresch",
            "mobile": "532-789-5232"
          }, {
            "email": "hmartinie14@csmonitor.com",
            "password": "xESNmRl3",
            "firstName": "Yóu",
            "lastName": "Martinie",
            "mobile": "909-611-5135"
          }, {
            "email": "tdurand15@examiner.com",
            "password": "uMnLZG",
            "firstName": "Eléa",
            "lastName": "Durand",
            "mobile": "216-129-6263"
          }, {
            "email": "mcoutts16@berkeley.edu",
            "password": "knKiLa",
            "firstName": "Kuí",
            "lastName": "Coutts",
            "mobile": "585-614-7904"
          }, {
            "email": "stimms17@paypal.com",
            "password": "Y1u8u1",
            "firstName": "Yú",
            "lastName": "Timms",
            "mobile": "958-405-2801"
          }, {
            "email": "cseatter18@pbs.org",
            "password": "iheD1JNwJF",
            "firstName": "Méline",
            "lastName": "Seatter",
            "mobile": "432-991-6164"
          }, {
            "email": "sgossage19@elpais.com",
            "password": "jUAtgOTJ1",
            "firstName": "Andréanne",
            "lastName": "Gossage",
            "mobile": "533-852-5665"
          }, {
            "email": "kstivens1a@twitter.com",
            "password": "rFsdhoYc",
            "firstName": "Noémie",
            "lastName": "Stivens",
            "mobile": "603-710-2791"
          }, {
            "email": "etome1b@dailymail.co.uk",
            "password": "27fbNQ",
            "firstName": "Annotée",
            "lastName": "Tome",
            "mobile": "783-356-6272"
          }, {
            "email": "bgearty1c@sfgate.com",
            "password": "QoiEo9ytier7",
            "firstName": "Simplifiés",
            "lastName": "Gearty",
            "mobile": "770-247-3106"
          }, {
            "email": "lblakeman1d@huffingtonpost.com",
            "password": "Z4JK2NKrY",
            "firstName": "Léana",
            "lastName": "Blakeman",
            "mobile": "600-334-8913"
          }, {
            "email": "gjex1e@gov.uk",
            "password": "SnHiEEOFIluV",
            "firstName": "Liè",
            "lastName": "Jex",
            "mobile": "949-990-7765"
          }, {
            "email": "atoffaloni1f@plala.or.jp",
            "password": "qE2x5Mt",
            "firstName": "Naëlle",
            "lastName": "Toffaloni",
            "mobile": "473-753-9555"
          }, {
            "email": "cdannehl1g@mediafire.com",
            "password": "5wYmYGrrEm",
            "firstName": "Simplifiés",
            "lastName": "Dannehl",
            "mobile": "575-630-9505"
          }, {
            "email": "sferney1h@163.com",
            "password": "tPR9wXqy",
            "firstName": "Félicie",
            "lastName": "Ferney",
            "mobile": "702-171-7734"
          }, {
            "email": "msurgeon1i@tinypic.com",
            "password": "hiNjwx3OZA",
            "firstName": "Kallisté",
            "lastName": "Surgeon",
            "mobile": "190-395-1939"
          }, {
            "email": "mminers1j@adobe.com",
            "password": "0UQWBAyY",
            "firstName": "Tú",
            "lastName": "Miners",
            "mobile": "638-155-5783"
          }, {
            "email": "hstanbrooke1k@state.tx.us",
            "password": "BsgSh4FO",
            "firstName": "Irène",
            "lastName": "Stanbrooke",
            "mobile": "249-301-4940"
          }, {
            "email": "wokeevan1l@archive.org",
            "password": "b0LQNLl",
            "firstName": "Anaé",
            "lastName": "O'Keevan",
            "mobile": "538-809-2813"
          }, {
            "email": "ssamter1m@webeden.co.uk",
            "password": "DOOXBtps",
            "firstName": "Léa",
            "lastName": "Samter",
            "mobile": "488-804-5271"
          }, {
            "email": "nbrierton1n@nhs.uk",
            "password": "CcSy6JYM",
            "firstName": "Michèle",
            "lastName": "Brierton",
            "mobile": "309-686-7950"
          }, {
            "email": "dhargess1o@last.fm",
            "password": "8qN4BrmrS1",
            "firstName": "Séverine",
            "lastName": "Hargess",
            "mobile": "448-381-8417"
          }, {
            "email": "fjean1p@elpais.com",
            "password": "5bkDDcOFr",
            "firstName": "Béatrice",
            "lastName": "Jean",
            "mobile": "263-192-1170"
          }, {
            "email": "bmcaw1q@imdb.com",
            "password": "zK9Z8DgZRp5F",
            "firstName": "Yáo",
            "lastName": "McAw",
            "mobile": "705-578-7511"
          }, {
            "email": "ssturm1r@businessinsider.com",
            "password": "tLqlj8win3",
            "firstName": "Aurélie",
            "lastName": "Sturm",
            "mobile": "886-536-7947"
          }, {
            "email": "bpickworth1s@ocn.ne.jp",
            "password": "O1xoHsv",
            "firstName": "Daphnée",
            "lastName": "Pickworth",
            "mobile": "204-328-8967"
          }, {
            "email": "pjacmard1t@mysql.com",
            "password": "8eXax6jy",
            "firstName": "Görel",
            "lastName": "Jacmard",
            "mobile": "624-776-5178"
          }, {
            "email": "dharwood1u@blogspot.com",
            "password": "1HQui9cjIhq",
            "firstName": "Léana",
            "lastName": "Harwood",
            "mobile": "688-562-6916"
          }, {
            "email": "gaulton1v@china.com.cn",
            "password": "nVxfHm",
            "firstName": "Cléopatre",
            "lastName": "Aulton",
            "mobile": "349-320-7031"
          }, {
            "email": "cbogey1w@telegraph.co.uk",
            "password": "LZbMkbb8SxOD",
            "firstName": "Styrbjörn",
            "lastName": "Bogey",
            "mobile": "391-653-8990"
          }, {
            "email": "gbratton1x@smugmug.com",
            "password": "DrgGf8M",
            "firstName": "Séverine",
            "lastName": "Bratton",
            "mobile": "620-843-3778"
          }, {
            "email": "sthorogood1y@cbc.ca",
            "password": "DpUsZZJib3dE",
            "firstName": "Sòng",
            "lastName": "Thorogood",
            "mobile": "731-454-3508"
          }, {
            "email": "wbeckford1z@bluehost.com",
            "password": "GBpoK5ZSO",
            "firstName": "Åke",
            "lastName": "Beckford",
            "mobile": "913-716-4343"
          }, {
            "email": "cgrandin20@geocities.com",
            "password": "mZkTNM",
            "firstName": "Clémence",
            "lastName": "Grandin",
            "mobile": "680-250-2892"
          }, {
            "email": "lprobey21@hubpages.com",
            "password": "MO7imZ",
            "firstName": "Cécilia",
            "lastName": "Probey",
            "mobile": "454-549-9116"
          }, {
            "email": "swebburn22@amazon.co.uk",
            "password": "M4ZPRv",
            "firstName": "Lèi",
            "lastName": "Webburn",
            "mobile": "368-282-9899"
          }, {
            "email": "kpakenham23@ucla.edu",
            "password": "T1VEqdE",
            "firstName": "Aloïs",
            "lastName": "Pakenham",
            "mobile": "117-830-7490"
          }, {
            "email": "akestin24@utexas.edu",
            "password": "oFWdaTAq65um",
            "firstName": "Ráo",
            "lastName": "Kestin",
            "mobile": "320-466-2899"
          }, {
            "email": "rpech25@stumbleupon.com",
            "password": "tslBe8JJqJM",
            "firstName": "Frédérique",
            "lastName": "Pech",
            "mobile": "615-617-3775"
          }, {
            "email": "toxtoby26@google.com.au",
            "password": "oqELq2l",
            "firstName": "Publicité",
            "lastName": "Oxtoby",
            "mobile": "996-938-9599"
          }, {
            "email": "ndavidsen27@cnn.com",
            "password": "kXBdWWF",
            "firstName": "Lèi",
            "lastName": "Davidsen",
            "mobile": "732-959-2755"
          }, {
            "email": "kmacrory28@oaic.gov.au",
            "password": "Baw9mE",
            "firstName": "Dafnée",
            "lastName": "MacRory",
            "mobile": "948-623-7602"
          }, {
            "email": "ctrudgion29@hp.com",
            "password": "TJqP2BGq",
            "firstName": "Esbjörn",
            "lastName": "Trudgion",
            "mobile": "396-915-2867"
          }, {
            "email": "pnials2a@eventbrite.com",
            "password": "ocEXBlccxw",
            "firstName": "Torbjörn",
            "lastName": "Nials",
            "mobile": "225-635-1501"
          }, {
            "email": "lzambon2b@privacy.gov.au",
            "password": "ZrbwI54pyNo",
            "firstName": "Dafnée",
            "lastName": "Zambon",
            "mobile": "945-875-6320"
          }, {
            "email": "hmacartney2c@51.la",
            "password": "pxVTuRF6T",
            "firstName": "Lauréna",
            "lastName": "Macartney",
            "mobile": "184-496-7554"
          }, {
            "email": "lbrosini2d@latimes.com",
            "password": "IVnO5B",
            "firstName": "Stéphanie",
            "lastName": "Brosini",
            "mobile": "104-494-7469"
          }, {
            "email": "lpenketh2e@goo.ne.jp",
            "password": "argkwB0Nip",
            "firstName": "Adélaïde",
            "lastName": "Penketh",
            "mobile": "203-208-9923"
          }, {
            "email": "vkundert2f@businessinsider.com",
            "password": "f4sfwo6Zy",
            "firstName": "Åslög",
            "lastName": "Kundert",
            "mobile": "539-712-3029"
          }, {
            "email": "kdubber2g@bluehost.com",
            "password": "MQwWOg9ozSP6",
            "firstName": "Bérengère",
            "lastName": "Dubber",
            "mobile": "612-288-6217"
          }, {
            "email": "sbool2h@mapquest.com",
            "password": "UvDzNvUFCBEj",
            "firstName": "Gérald",
            "lastName": "Bool",
            "mobile": "979-351-9456"
          }, {
            "email": "aluca2i@artisteer.com",
            "password": "H5QzTKS",
            "firstName": "Vénus",
            "lastName": "Luca",
            "mobile": "809-867-8241"
          }, {
            "email": "mmucklow2j@eventbrite.com",
            "password": "Kz5rxrUBbbt",
            "firstName": "Dà",
            "lastName": "Mucklow",
            "mobile": "267-621-6800"
          }, {
            "email": "jcostigan2k@irs.gov",
            "password": "ql4JLQEs",
            "firstName": "Léana",
            "lastName": "Costigan",
            "mobile": "571-465-3361"
          }, {
            "email": "bwiltshire2l@ca.gov",
            "password": "TMD58O",
            "firstName": "Naéva",
            "lastName": "Wiltshire",
            "mobile": "738-755-1404"
          }, {
            "email": "sosgar2m@aboutads.info",
            "password": "KPKuOrb4XMu",
            "firstName": "Léana",
            "lastName": "Osgar",
            "mobile": "370-399-4718"
          }, {
            "email": "sclogg2n@adobe.com",
            "password": "bAEnFS09BEK",
            "firstName": "Uò",
            "lastName": "Clogg",
            "mobile": "719-763-4526"
          }, {
            "email": "jpeggrem2o@apache.org",
            "password": "0t3Qbj",
            "firstName": "André",
            "lastName": "Peggrem",
            "mobile": "726-655-1658"
          }, {
            "email": "rberesfore2p@photobucket.com",
            "password": "MZ99nw",
            "firstName": "Yè",
            "lastName": "Beresfore",
            "mobile": "683-996-1585"
          }, {
            "email": "czukerman2q@indiegogo.com",
            "password": "knZjsukqzZ",
            "firstName": "Annotés",
            "lastName": "Zukerman",
            "mobile": "697-840-6387"
          }, {
            "email": "mvenditto2r@answers.com",
            "password": "Esgz6tzYYp",
            "firstName": "Tú",
            "lastName": "Venditto",
            "mobile": "547-112-6387"
          }
        
        ]
          
        items.forEach(item => {
            item.createdAt = Sequelize.literal('NOW()');
            item.updatedAt = Sequelize.literal('NOW()');
        });
        await queryInterface.bulkInsert('Users', items, {});
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('Users', null, {});
    }
};
